# Menus
bindd = SUPER, SPACE, Open launcher, exec, $launcher
bindd = SUPER ALT, SPACE, System menu, exec, $hypr_scripts/hypr-sys-menu
# bindd = SUPER ALT, SPACE, Search files, exec, $hypr_scripts/hypr-search-home
bindd = SUPER CTRL, SPACE, Open run launcher, exec, $launcher_run
bindd = SUPER CTRL, V, List virtual machines, exec, $hypr_scripts/hypr-list-vm
bindd = SUPER CTRL, Q, System menu, exec, $logout
bindd = SUPER, comma, Edit config files, exec, $hypr_scripts/hypr-edit-config
bindd = SUPER, XF86AudioMute, Show keyboard bindings, exec, $hypr_scripts/hypr-show-keybinds
bindd = SUPER, F1, Show keyboard bindings, exec, $hypr_scripts/hypr-show-keybinds
bindd = ,Help , Show keyboard bindings, exec, $hypr_scripts/hypr-show-keybinds
bindd = SUPER, P, Monitors menu, exec, $hypr_scripts/hypr-switch-monitor
bindd = SUPER ALT, Q, Exit Hyprland, exec, hyprctl dispatch exit

# Aesthetics
bindd = SUPER,XF86MonBrightnessDown, Previous wallpaper, exec, variety -p && sleep 1.5 && notify-send "Fondo de pantalla" "Nuevo fondo: $(variety --current 2> /dev/null | xargs -0 -- basename)"
bindd = SUPER,XF86MonBrightnessUp, Next wallpaper, exec, variety -n && sleep 1.5 && notify-send "Fondo de pantalla" "Nuevo fondo: $(variety --current 2> /dev/null | xargs -0 -- basename)"
bindd = SUPER ALT, R, Reset Waybar, exec, $hypr_scripts/hypr-restore-waybar
bindd = SUPER, XF86Favorites, Reset Waybar, exec, $hypr_scripts/hypr-restore-waybar

# Screenshots
bindd = ,Print, Save screenshot to file, exec, $hypr_scripts/hypr-cmd-screenshot file
bindd = SUPER SHIFT ALT, S, Save screen area to file, exec, $hypr_scripts/hypr-cmd-screenshot region
bindd = SUPER SHIFT, S, Copy screen area to clipboard, exec, $hypr_scripts/hypr-cmd-screenshot
bindd = SUPER SHIFT CTRL, S, Color picker, exec, pkill hyprpicker || hyprpicker -a

# Keyboard
bindd = SUPER SHIFT, SPACE, Switch keyboard layout, exec, $hypr_scripts/hypr-switch-keyboard-layout
# trigger when the switch is turning off

binddl= ,switch:on:Lid Switch, Disable screen on close lid, exec, hyprctl keyword monitor "eDP-1, disable"
binddl= ,switch:off:Lid Switch, Enable screen on open lid, exec, hyprctl keyword monitor "eDP-1, preferred, auto, 1"


