#      _    _                 _ _   _
#     / \  | | __ _  ___ _ __(_) |_| |_ _   _
#    / _ \ | |/ _` |/ __| '__| | __| __| | | |
#   / ___ \| | (_| | (__| |  | | |_| |_| |_| |
#  /_/   \_\_|\__,_|\___|_|  |_|\__|\__|\__, |
#                                       |___/


[general]
live_config_reload = true
# import = ["~/.config/alacritty/themes/TomorrowNight.toml"]
import = ["~/.config/alacritty/themes/CatppuccinMocha.toml"]
# import = ["~/.config/alacritty/themes/Dracula.toml"]
# import = ["~/.config/alacritty/themes/Nord.toml"]
# import = ["~/.config/alacritty/themes/GruvboxDark.toml"]

working_directory = "/home/daniel"

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 17

[font.glyph_offset]
y = 3

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.offset]
y = 6

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[window]
decorations = "Full"
# decorations = "None"
opacity = 0.7
blur = false

[window.dimensions]
columns = 110
lines = 30

[window.padding]
x = 10
y = 10
