#      _    _                 _ _   _
#     / \  | | __ _  ___ _ __(_) |_| |_ _   _
#    / _ \ | |/ _` |/ __| '__| | __| __| | | |
#   / ___ \| | (_| | (__| |  | | |_| |_| |_| |
#  /_/   \_\_|\__,_|\___|_|  |_|\__|\__|\__, |
#                                       |___/

live_config_reload = true
# import = ["~/.config/alacritty/themes/TomorrowNight.toml"]
import = ["~/.config/alacritty/themes/CatppuccinMocha.toml"]
# import = ["~/.config/alacritty/themes/Dracula.toml"]
# import = ["~/.config/alacritty/themes/Nord.toml"]
# import = ["~/.config/alacritty/themes/GruvboxDark.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 16

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold ItaliBold Italic"

[font.glyph_offset]
y = 2

[font.italic]
style = "Italic"

[font.normal]
# family = "Noto Sans Mono"
# family = "Monospace"
# family = "Jetbrains Mono"
# family = "CodeNewRoman Nerd Font Mono"
# family = "MesloLGM Nerd Font Mono"
# family = "FiraCode Nerd Font Mono"
# family = "SF Mono"
family = "MesloLGS NF"
# family = "Monaspace Radon"
style = "Medium"

[font.offset]
y = 4

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[window]
decorations = "full"
opacity = 0.9
blur = true

[window.dimensions]
columns = 110
lines = 30

[window.padding]
x = 10
y = 10
