#      _    _                 _ _   _
#     / \  | | __ _  ___ _ __(_) |_| |_ _   _
#    / _ \ | |/ _` |/ __| '__| | __| __| | | |
#   / ___ \| | (_| | (__| |  | | |_| |_| |_| |
#  /_/   \_\_|\__,_|\___|_|  |_|\__|\__|\__, |
#                                       |___/


[general]
live_config_reload = true
# import = ["~/.config/alacritty/themes/TomorrowNight.toml"]
import = ["~/.config/alacritty/themes/CatppuccinMocha.toml"]
# import = ["~/.config/alacritty/themes/Dracula.toml"]
# import = ["~/.config/alacritty/themes/Nord.toml"]
# import = ["~/.config/alacritty/themes/GruvboxDark.toml"]

working_directory = "/home/daniel"

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 17

[font.glyph_offset]
y = 2

[font.normal]
# family = "Noto Sans Mono"
# family = "Cousine Nerd Font Mono"
# family = "GeistMono Nerd Font"
# family = "Inconsolata Nerd Font"
# family = "DejaVuSansM Nerd Font"
# family = "Hasklug Nerd Font"
# family = "Hack Nerd Font"
# family = "Monospace"
# family = "JetBrainsMono Nerd Font"
# family = "CodeNewRoman Nerd Font"
# family = "DejaVu Sans Mono"
# family = "RobotoMono Nerd Font"
# family = "MesloLGL Nerd Font"
family = "MesloLGM Nerd Font"
# family = "FiraCode Nerd Font"
# family = "SF Mono"
# family = "Monaspace Radon"
# family = "Monaspace Neon"
style = "Regular"

[font.offset]
y = 4

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[window]
decorations = "Full"
opacity = 0.85
blur = false

[window.dimensions]
columns = 110
lines = 30

[window.padding]
x = 10
y = 10
