#!/bin/bash

############################
# .make.sh
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################

########## Variables

# dotfiles directory
DOTFILESDIR=$HOME/dotfiles
# dotconfig dirs
DOTCONFIGS="alacritty bspwm dunst fastfetch hypr i3 kitty mako noctalia noctalia-shell nvim picom polybar quickshell rofi starship sway swaylock sxhkd tmux waybar wlogout wofi zsh"
C_GREEN="\e[32m"
C_RED="\e[31m"
C_RESET="\e[0m\e[27m"
C_ERROR="\e[31m\e[7m"

files=".bashrc .vimrc .vim/plugins.vim .bash_aliases .bash_prompt .dircolors .inputrc bash_profile .gitconfig .tmux.conf gitignore"    # list of files/folders to symlink in homedir

##########
print_error() {
    echo -e "${C_ERROR} ERROR ${C_RESET}  ${1}"
    exit 1
}

install_dotfile() {
    echo "Installing dotfile: $PKG..."
    if [ -h "$XDG_CONFIG_HOME/$PKG" ]; then
        echo "Symlink \"$XDG_CONFIG_HOME/$PKG\" existe, eliminandolo"
        rm $XDG_CONFIG_HOME/$PKG
    elif [ -d "$XDG_CONFIG_HOME/$PKG" ]; then
        echo "Directorio \"$XDG_CONFIG_HOME/$PKG\" existe, realizando backup"
        mv "$XDG_CONFIG_HOME/$PKG" "$XDG_CONFIG_HOME/$PKG.bak"
    else
        echo "Directorio \"$XDG_CONFIG_HOME/$PKG\" no existe"
    fi
    echo "Creando symlink \"$XDG_CONFIG_HOME/$PKG\" --> \"$DOTFILESDIR/dotconfig/$PKG\""
    ln -s $DOTFILESDIR/dotconfig/$PKG $XDG_CONFIG_HOME/$PKG
}

# echo -e "${C_GREEN}Install dotfiles${C_RESET}"
if [ -n "$1" ]; then
    if [ $(echo $DOTCONFIGS | grep -s $1) ]; then
        install_dotfile $1
    else
        print_error "Dotfile \"$1\" no existe."
    fi
else
    echo "Select dotfile to install..."
    PKG=$(echo $DOTCONFIGS | tr " " "\n" | fzf)
    if [ -z "$PKG" ]; then
        print_error "No se seleccionó dotfile."
        exit 1
    fi
    install_dotfile $PKG
fi

