#!/bin/bash

############################
# .make.sh
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################

########## Variables

dir=~/dotfiles                    # dotfiles directory
files=".bashrc .vimrc .vim/plugins.vim .bash_aliases .bash_prompt .dircolors .inputrc .bash_profile .gitconfig .tmux.conf gitignore"    # list of files/folders to symlink in homedir

##########

# create symlinks from the homedir to any files in the ~/dotfiles directory specified in $files
echo "Installing dotfiles"
for file in $files; do
    echo ""
    echo "Processing file $file..."
    #check if exists dotfile
    if [[ -f $dir/$file ]]; then
        echo "   $dir/$file exists in directory dotfiles"

        if [[ -e ~/$file || -h $dir/$file ]]; then
            echo "   ~/$file exists in home directory"
            echo "   Deleting ~/$file"
            rm ~/$file
        else
            echo "   ~/$file does not exists in home directory"
        fi
        echo "   Creating symlink from $dir/$file to ~/$file"
        ln -s $dir/$file ~/$file
    else
        echo "   $dir/$file does not exists in directory dotfiles"
    fi
done

