#!/usr/bin/bash

INSTALL_USERNAME=daniel

set -e
RED='\e[31m'
YELLOW='\e[33m'
GREEN='\e[32m'
VINVERSE='\e[7m'
NC='\e[0m' # No Color

print_success() {
    echo -e "${GREEN}$1${NC}"
}

print_error() {
    echo -e "${RED}$1${NC}"
}

print_info() {
    echo -e "${YELLOW}$1${NC}"
}

# update system
print_info "Updating system packages..."
sudo apt update; sudo apt -y upgrade


echo
print_info "Install command line tools..."
sudo apt install -y zsh fzf fd-find zoxide starship tmux fastfetch trash-cli btop xdg-user-dirs neovim


echo
print_info "Configuring shell..."
xdg-user-dirs-update
[ -d "$HOME/.config" ]           || { mkdir -p $HOME/.config          && echo "Create folder .config"; }
[ -d "$HOME/.cache" ]            || { mkdir -p $HOME/.cache           && echo "Create folder .cache"; }
[ -d "$HOME/.local/share" ]      || { mkdir -p $HOME/.local/share     && echo "Create folder .local/share"; }
[ -d "$HOME/.local/state/zsh" ]  || { mkdir -p $HOME/.local/state/zsh && echo "Create folder .local/state/zsh"; }
[ -d "$HOME/.config/zsh" ]       || { ln -s $HOME/dotfiles/dotconfig/zsh $HOME/.config/zsh && echo "Link folder .config/zsh"; }
[ -f "$HOME/.zshenv" ]           || { ln -s $HOME/dotfiles/dotconfig/zsh/.zshenv $HOME/.zshenv && echo "Link file .zshenv"; }
[ -d "$HOME/.config/starship" ]  || { ln -s $HOME/dotfiles/dotconfig/starship  $HOME/.config/starship && echo "Link folder .config/starship"; }
[ -d "$HOME/.config/fastfetch" ] || { ln -s $HOME/dotfiles/dotconfig/fastfetch $HOME/.config/fastfetch && echo "Link folder .config/fastfetch"; }
[ -d "$HOME/.config/nvim" ]      || { ln -s $HOME/dotfiles/dotconfig/nvim      $HOME/.config/nvim && echo "Link folder .config/nvim"; }


echo
print_info "Check current shell..."
if [ ! "$SHELL" = "/bin/zsh" ]; then
    print_info "Current shell: $SHELL, changing to zsh"
    chsh -s /bin/zsh $INSTALL_USERNAME
else
    print_success "OK, current shell is: $SHELL"
fi


echo
print_info "Creating config dir links..."
[ -d "$HOME/.config/rofi" ]      || ln -s $HOME/dotfiles/dotconfig/rofi      $HOME/.config/rofi
[ -d "$HOME/.config/kitty" ]     || ln -s $HOME/dotfiles/dotconfig/kitty     $HOME/.config/kitty
[ -d "$HOME/.config/mako" ]      || ln -s $HOME/dotfiles/dotconfig/mako      $HOME/.config/mako
[ -d "$HOME/.config/waybar" ]    || ln -s $HOME/dotfiles/dotconfig/waybar    $HOME/.config/waybar
[ -d "$HOME/.config/hypr" ]      || ln -s $HOME/dotfiles/dotconfig/hypr      $HOME/.config/hypr
[ -d "$HOME/.config/wlogout" ]   || ln -s $HOME/dotfiles/dotconfig/wlogout   $HOME/.config/wlogout


echo
print_info "Installing network, bluetooth..."
sudo apt install -y network-manager firewalld polkitd bluez bluez-tools


echo
print_info "Installing desktop environment"
if [ ! grep -q trixie-backports /etc/apt/sources.list ]; then
    echo "Add trixie-backports"
    echo "deb http://deb.debian.org/debian/ trixie-backports main contrib non-free" | sudo tee -a /etc/apt/sources.list
fi
sudo apt install -y -t trixie-backports hyprland hyprland-guiutils hyprlock hyprpicker hyprpolkitagent hypridle xdg-desktop-portal xdg-desktop-portal-hyprland kitty
sudo apt install -y uwsm wayland-utils wayland lightdm wlr-randr qt6-wayland grim slurp mako-notifier brightnessctl wlsunset wlogout
sudo apt install -y thunar firefox-esr rofi
#
# install apps
# print_info "Installing apps"
