#  __  __             _ _
# |  \/  | ___  _ __ (_) |_ ___  _ __ ___
# | |\/| |/ _ \| '_ \| | __/ _ \| '__/ __|
# | |  | | (_) | | | | | || (_) | |  \__ \
# |_|  |_|\___/|_| |_|_|\__\___/|_|  |___/

env = GDK_SCALE,2

# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor=name,resolution,position,scale
monitor= ,preferred, auto, 1
monitor = eDP-1, preferred, 0x0, 1.25
monitor = DP-8, 3840x2160, 2240x0, 1.25

workspace = 1, monitor:eDP-1, persistent:true
workspace = 2, monitor:eDP-1, persistent:true
workspace = 3, monitor:eDP-1, persistent:true
workspace = 4, monitor:eDP-1, persistent:true
workspace = 5, monitor:eDP-1, persistent:true
workspace = 6, monitor:DP-8, persistent:true
workspace = 7, monitor:DP-8, persistent:true
workspace = 8, monitor:DP-8, persistent:true
workspace = 9, monitor:DP-8, persistent:true
workspace = 10, monitor:DP-8, persistent:true

