#             _
#  _ __ _   _| | ___  ___
# | '__| | | | |/ _ \/ __|
# | |  | |_| | |  __/\__ \
# |_|   \__,_|_|\___||___/
#

# Browsers
windowrule = workspace 1,class:^(Brave-browser)$
windowrule = workspace 1,class:^(brave-browser)$
windowrule = workspace 1,class:^(firefox)$
windowrule = workspace 1,class:^(org.mozilla.firefox)$
windowrule = workspace 1,class:^(Chromium-browser)$
windowrule = workspace 1,class:^(Org.chromium.Chromium)$
windowrule = tile,class:^(Chromium-browser)$
windowrule = tile, class:^(Org.chromium.Chromium)$
windowrule = noblur,class:^()$ # chrome-like browsers no blur menus

# File Managers
windowrule = workspace 4,class:^(thunar)$
windowrule = workspace 4,class:^(org.gnome.nautilus)$

# virt-manager
windowrule = workspace 3,class:^(virt-manager)$
windowrule = workspace 3,class:^(virt-viewer)$
windowrule = fullscreenstate 0 2, class:^(virt-viewer)$

# rofi / wofi
windowrule = pin,class:^(Rofi)$
windowrule = pin,class:^(wofi)$
windowrule = dimaround on,class:^(wofi)$
layerrule = blur, rofi
layerrule = noanim, rofi
layerrule = dimaround, rofi

# Variety
windowrule = float, class:^(variety)$
windowrule = size 100% 5%, class:^(variety)$,title:^(Imágenes de Variety)$
windowrule = move 0% 90%, class:^(variety)$,title:^(Imágenes de Variety)$

# Aesthtics
layerrule = blur, waybar
layerrule = ignorealpha, waybar
layerrule = blur, logout_dialog
layerrule = noanim, wallpaper
layerrule = animation slide right, notifications
# windowrule = opacity 1.0 0.95, class:.*

# System
windowrule = float, class:^(hypr-sys-menu)$
windowrule = center, class:^(hypr-sys-menu)$
windowrule = size 1400 900, class:^(hypr-sys-menu)$
windowrule = float, class:^(xdg-desktop-portal-gtk)$

# Others
windowrule = float, class:^(org.gnome.Calculator)$
windowrule = tile, title:(Microsoft Excel)
windowrule = tile, title:(Gaia Sky)
windowrule = float, class:^(dosbox)$
windowrule = float, class:^(io.github.josephmawa.Bella)$
windowrule = float, class:^(org.gnome.World.PikaBackup)$

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# no gaps, borders, rounding on tiled windows when there's only one (w[t1]) ----------
# workspace = w[t1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[t1]
# windowrule = rounding 0, floating:0, onworkspace:w[t1]
# no gaps, borders, rounding on grouped windows when there's only one (w[tg1]) -------
# workspace = w[tg1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tg1]
# windowrule = rounding 0, floating:0, onworkspace:w[tg1]
# no gaps, borders, rounding on fullscreen windows -----------------------------------
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]

