#              _            _             _
#   __ _ _   _| |_ ___  ___| |_ __ _ _ __| |_
#  / _` | | | | __/ _ \/ __| __/ _` | '__| __|
# | (_| | |_| | || (_) \__ \ || (_| | |  | |_
#  \__,_|\__,_|\__\___/|___/\__\__,_|_|   \__|
#

# Execute your favorite apps at launch
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland
exec-once = waybar
# exec-once = qs
exec-once = systemctl --user start hyprpolkitagent
exec-once = mako
# exec-once = /usr/bin/variety
exec-once = $HOME/.config/hypr/scripts/hypr-set-wallpaper
exec-once = wlsunset -l -33 -L -70
exec-once = dropbox start
# exec-once = xhost +SI:localuser:root
exec-once = hypridle

# exec-once = flameshot

