#!/bin/sh

fg=3 bg=4
for j in fg bg; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
for i in {0..7}; do
    printf -v fbright$i %b "\e[9${i}m"
done
bld=$'\e[1m'
rst=$'\e[0m'
inv=$'\e[7m'

cat <<EOF
${fg1}                             .-"""-.    ${fg4}__
${fg1}                            /       \\${fg4}.q####p.
${fg1}                         __:  ${fg7}db     ${fg1}#${fg4}#######b.
${fg1}                  _._.-""  :  ${fg7}#"b.   ${fg1}:${fg4}###S#####b
${fg1}                .'   "-.  "   ${fg7}T. \`b d${fg4}###S#S####P^${fg1}.              ${fg7}.-,
${fg1}    ${fg4}.qp.       ${fg1}:        \`.     ${fg7}TsP' ${fg1}T${fg4}SSS#P'S#P'   ${fg1}\`.            ${fg7}\`dP
${fg4} ,q#####b      ${fg1};b         \  '.     /${fg4}"T#P  :P       ${fg1}\`.      ${fg7}__ dP_${fg1},
${fg4} :####SS#b_    ##b${fg1}.  __.   ;${fg4}_  ${fg1}\`-._/   ${fg4}Y    ${fg1}\         \`.   ${fg7}( dP"${fg1}.';
${fg4} #######S##b.  :S###p${fg1}._    ${fg4}####p${fg1}./      ;    "-._       \`--${fg7}dP ${fg1}.'  ;
${fg4}:####P${fg1}^^${fg4}TS###b  SS######   'T####b.     ${fg1};        ""--.   ${fg7}dP  ${fg1}/   /
${fg4}####P    :####bd#SSS###${fg1};\  . ${fg4}"^####b${fg1}___/            ${fg7}__${fg1}\\${fg7}dP ${fg1}.-"_.-"
${fg4}###P     ######b\`T#SSS#  ${fg1}"-.J   ${fg4}"^T#/  ${fg1}""-._       ${fg7}( dP${fg1}\ /   /
${fg4}:##      ${fg1}; T${fg4}####b.\`T##;     d#+${fg1}.     ""-.   ""--.._${fg7}dP${fg1}-, \`._."
${fg4} T${fg1};     :   T${fg4}#####b.\`^'   _d#P .#p${fg1}.___   "         \`-'
${fg1}  \`.    ;    T${fg4}######b._.dS### :###b${fg1}"--..__..---${fg7}g${fg1},   \\
${fg1}    \`. :      ${fg4}##########S###P${fg1}\ ${fg4}TP^${fg1}"\       ${fg7},-dP ${fg1};    ;
${fg1}      \;   .-'${fg4}#######SSSP^^"  ${fg1}\     \`._,-.-${fg7}dP-' ${fg1}|    ;
${fg1}       :     :${fg4}"^^"" """        ${fg1}\`.   \`._:'.\`.\   :    ;\\
${fg1}        \  , :                   "-. (,j\ \` /   ;\(// \\
${fg1}         \`:   \                     ${fg7}"dP${fg1}__.-"    '-\\   \;
${fg1}           \   :                ${fg7}.--dP,             ${fg1}\;
${fg1}            \`--'                ${fg7}\`dP\`-'
${fg7}                              .-j
${fg7}                              \`-:_
${fg7}                                 \)
${fg7}                                  \`--'${rst}
EOF

