#!/bin/bash

############################
# INSTALL NEOVIM
############################

########## Variables

dir=~/dotfiles                    # dotfiles directory
files=".vimrc .vim/plugins.vim"    # list of files/folders to symlink in homedir
neovimconfig=~/.config/nvim
##########

# Instala neovim
sudo apt update | sudo apt install -y neovim

# Instala Vundle package manager
if [[ ! -d ~/.vim/bundle/Vundle.vim ]]; then
    echo "   Instala Vundle"
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

if [[ ! -d "$neovimconfig" ]]; then
    echo "   Agrega directorio configuracion nvim"
    mkdir $neovimconfig
fi

if [[ ! -f "$neovimconfig/init.vim" ]]; then
    echo "   Agrega source en init.vim"
    echo "source ~/.vimrc" > $neovimconfig/init.vim
fi

# create symlinks from the homedir to any files in the ~/dotfiles directory specified in $files
echo "Installing NEOVIM"
for file in $files; do
    #check if exists dotfile
    if [[ -f $dir/$file ]]; then
        echo "   $dir/$file exists in directory dotfiles"

        if [[ -e ~/$file || -h $dir/$file ]]; then
            echo "   ~/$file exists in home directory"
            echo "   Deleting ~/$file"
            rm ~/$file
        else
            echo "   ~/$file does not exists in home directory"
        fi
        echo "   Creating symlink from $dir/$file to ~/$file"
        ln -s $dir/$file ~/$file
    else
        echo "   $dir/$file does not exists in directory dotfiles"
    fi
done

