#!/bin/bash

############################
# INSTALL ZSH
############################

########## Variables

dir=~/dotfiles                    # dotfiles directory
files=".zshrc .tmux.conf"    # list of files/folders to symlink in homedir
##########

# Instala zsh y ohmyzsh
sudo apt update | sudo apt install -y zsh curl tmux fd-find
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"


# create symlinks from the homedir to any files in the ~/dotfiles directory specified in $files
echo "Installing ZSH"
for file in $files; do
    #check if exists dotfile
    if [[ -f $dir/$file ]]; then
        echo "   $dir/$file exists in directory dotfiles"

        if [[ -e ~/$file || -h $dir/$file ]]; then
            echo "   ~/$file exists in home directory"
            echo "   Deleting ~/$file"
            rm ~/$file
        else
            echo "   ~/$file does not exists in home directory"
        fi
        echo "   Creating symlink from $dir/$file to ~/$file"
        ln -s $dir/$file ~/$file
    else
        echo "   $dir/$file does not exists in directory dotfiles"
    fi
done

