#!/usr/bin/bash

set -e
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

print_success() {
  echo -e "${GREEN}$1${NC}"
}

print_error() {
  echo -e "${RED}$1${NC}"
}

print_info() {
  echo -e "${YELLOW}$1${NC}"
}

# update system
print_info "Updating system packages"
sudo apt update
sudo apt upgrade
# echo "deb http://deb.debian.org/debian/ trixie-backports main contrib non-free" | sudo tee -a /etc/apt/sources.list

# install basic programs
print_info "Installing basic packages"
sudo apt install -y git neovim xdg-user-dirs
sudo apt install -y zsh fzf fd-find zoxide starship tmux fastfetch trash-cli

print_info "Creating basic dirs"
xdg-user-dirs-update
[ -d "$HOME/.config" ]          || mkdir -p $HOME/.config
[ -d "$HOME/.cache" ]           || mkdir -p $HOME/.cache
[ -d "$HOME/.local/share" ]     || mkdir -p $HOME/.local/share
[ -d "$HOME/.local/state/zsh" ] || mkdir -p $HOME/.local/state/zsh

print_info "Creating config dir links"
[ -d "$HOME/.config/nvim" ]      || ln -s $HOME/dotfiles/dotconfig/nvim      $HOME/.config/nvim
[ -d "$HOME/.config/zsh" ]       || ln -s $HOME/dotfiles/dotconfig/zsh       $HOME/.config/zsh
[ -d "$HOME/.config/starship" ]  || ln -s $HOME/dotfiles/dotconfig/starship  $HOME/.config/starship
[ -d "$HOME/.config/rofi" ]      || ln -s $HOME/dotfiles/dotconfig/rofi      $HOME/.config/rofi
[ -d "$HOME/.config/kitty" ]     || ln -s $HOME/dotfiles/dotconfig/kitty     $HOME/.config/kitty
[ -d "$HOME/.config/fastfetch" ] || ln -s $HOME/dotfiles/dotconfig/fastfetch $HOME/.config/fastfetch
[ -d "$HOME/.config/mako" ]      || ln -s $HOME/dotfiles/dotconfig/mako      $HOME/.config/mako
[ -d "$HOME/.config/waybar" ]    || ln -s $HOME/dotfiles/dotconfig/waybar    $HOME/.config/waybar
[ -d "$HOME/.config/hypr" ]      || ln -s $HOME/dotfiles/dotconfig/hypr      $HOME/.config/hypr
[ -f "$HOME/.zshenv" ]           || ln -s $HOME/dotfiles/dotconfig/zsh/.zshenv $HOME/.zshenv

# install network manager
print_info "Installing network, bluetooth"
sudo apt install -y network-manager firewalld polkitd bluez bluez-tools
#
# install desktop environment
print_info "Installing desktop environment"
sudo apt install -y -t trixie-backports hyprland hyprland-guiutils hyprlock hyprpicker hyprpolkitagent hypridle
sudo apt install -y lightdm wlr-randr xdg-desktop-portal xdg-desktop-portal-wlr swaylock swaybg lxqt-policykit qt6-wayland grim slurp mako-notifier brightnessctl
sudo apt install -y kitty thunar firefox-esr rofi waybar
#
# install apps
print_info "Installing apps"
