theme_name = "catppuccin"

[palette]
rosewater = "#F5E0DC"
flamingo =  "#F2CDCD"
pink =      "#F5C2E7"
mauve =     "#CBA6F7"
red =       "#F38BA8"
maroon =    "#EBA0AC"
peach =     "#FAB387"
yellow =    "#F9E2AF"
green =     "#A6E3A1"
teal =      "#94E2D5"
sky =       "#89DCEB"
sapphire =  "#74C7EC"
blue =      "#89B4FA"
lavender =  "#B4BEFE"
text =      "#CDD6F4"
subtext1 =  "#BAC2DE"
subtext0 =  "#A6ADC8"
overlay2 =  "#9399B2"
overlay1 =  "#7F849C"
overlay0 =  "#6C7086"
surface2 =  "#585B70"
surface1 =  "#45475A"
surface0 =  "#313244"
base =      "#1E1E2E"
mantle =    "#181825"
crust =     "#11111B"

[roles]
window_active_border =   "sky"
window_active_border_2 = "lavender"
window_active_shadow =   { color = "base", alpha = 0.60 }
window_inactive_border = "overlay0"
window_inactive_shadow = { color = "crust", alpha = 0.50 }
window_group_active_border =   "peach"
window_group_inactive_border = "overlay0"
groupbar_active =   "peach"
groupbar_inactive = "overlay0"
groupbar_text =     "surface0"
bar_bg =     { color = "mantle", alpha = 0.70 }
tooltip_bg = { color = "mantle", alpha = 0.90 }
fg_normal =  { color = "text", alpha = 0.80 }
fg_high =    "text"
fg_disabled = { color = "text", alpha = 0.40 }
accent1 = "sapphire"
accent2 = "yellow"
accent3 = "mauve"
warning = "yellow"
critical = "red"
success = "green"
window_bg =  { color = "base", alpha = 0.80 }
textbox_bg = "surface1"
prompt_fg =  "blue"
prompt_bg =  { color = "base", alpha = 0.80 }
placeholder_fg = { color = "text", alpha = 0.30 }
selected_bg =    { color = "subtext1", alpha = 0.10 }
