#  ____                       _                   _
# |  _ \ _ __ __ _  ___ _   _| | __ _    ___ ___ | | ___  _ __ ___
# | | | | '__/ _` |/ __| | | | |/ _` |  / __/ _ \| |/ _ \| '__/ __|
# | |_| | | | (_| | (__| |_| | | (_| | | (_| (_) | | (_) | |  \__ \
# |____/|_|  \__,_|\___|\__,_|_|\__,_|  \___\___/|_|\___/|_|  |___/


$background = 282a36
$foreground = f8f8f2
$selection  = 44475a
$comment    = 6272a4
$red        = ff5555
$orange     = ffb86c
$yellow     = f1fa8c
$green      = 50fa7b
$purple     = bd93f9
$cyan       = 8be9fd
$pink       = ff79c6
$accent     = $purple


$color_active_border_1       = rgb($purple)
$color_active_border_2       = rgb($pink)
$color_inactive_border       = rgb($selection)
$color_group_border_active   = rgb($orange)
$color_group_border_inactive = rgb($selection)
$color_groupbar_active       = rgba($orangeCC)
$color_groupbar_inactive     = rgba($selection77)
$color_text_groupbar         = rgb($comment)
$color_shadow                = rgba($background77)
$color_shadow_inactive       = rgba(00000000)
