#!/bin/bash

OUTPUT_DIR=$HOME/Imágenes/Screenshots
OUTPUT_FILE=$OUTPUT_DIR/$(date +"%Y%m%d_%H%M%S.png")

notify() {
    notify-send -i camera-photo "Screenshot" "$1"
}

if [[ ! -d "$OUTPUT_DIR" ]]; then
  notify-send "Screenshot directory does not exist: $OUTPUT_DIR" -u critical -t 3000
  exit 1
fi

case "$1" in
    region | --region)
        case $DESKTOP_SESSION in
            bspwm)
                maim -s $OUTPUT_FILE
                notify "Area creado en archivo"
                ;;
            *)
                pkill slurp
                region=$(slurp 2> /dev/null)
                if [ -n "$region" ]; then
                    grim -g "$region" $OUTPUT_FILE
                    notify "Area creado en archivo"
                fi
                ;;
        esac
        ;;

    file | --file)
        case $DESKTOP_SESSION in
            bspwm) maim $OUTPUT_FILE ;;
            *)     grim $OUTPUT_FILE ;;
        esac
        notify "Pantalla creado en archivo"
        ;;

    *)
        case $DESKTOP_SESSION in
            bspwm)
                maim -s | xclip -selection clipboard -t image/png
                notify "Area creado en clipboard"
                ;;
            *)
                pkill slurp
                region=$(slurp 2> /dev/null)
                if [ -n "$region" ]; then
                    grim -g "$region" -t png - | wl-copy -t image/png;
                    notify "Area creado en clipboard"
                fi
                ;;
        esac
        ;;
esac

