#!/usr/bin/env bash

OPCIONES=$(
    virsh --connect qemu:///system list --all |
    sed -n 's/^[[:space:]]*[-[:digit:]+][[:space:]]*\([[:alnum:]_-]*\)[[:space:]]*\([[:alpha:]]*\)/\1 (\2)/p' |
    grep -v '^--'
)

font='Hack Nerd Font 16'
theme='prompt{enabled:false;} entry{placeholder:"Start VM...";} window{width:22%;}'

VM=$(printf '%s' "$OPCIONES" |
    rofi -dmenu -format p -theme-str "$theme" -font "$font" |
    cut -d " " -f 1
)

if [[ -n "$VM" ]]; then
    "$XDG_CONFIG_HOME/hypr/scripts/hypr-start-vm" "$VM"
fi
