#!/usr/bin/env bash

if [ "$DESKTOP_SESSION" = "bspwm" ]; then
    [[ "$(setxkbmap -query | grep layout | awk '{print $2}')" = us ]] && setxkbmap latam || setxkbmap us
    newlayout=$(setxkbmap -query | grep layout | awk '{print $2}')
else
    internal=at-translated-set-2-keyboard
    external=keychron

    echo "switch internal layout: $newlayout"
    hyprctl switchxkblayout $internal next

    newlayout="$(hyprctl devices -j | jq -r --arg keyb $internal '.keyboards[] | select(.name==$keyb).active_keymap')"
    echo "new internal layout: $newlayout"

    keyboards="$(hyprctl devices -j | jq -r '.keyboards[].name' | grep $external)"
    echo "keyboards: $keyboards"

    for keyb in $keyboards; do
        echo "external: $keyb"
        currlayout="xxx"
        echo "current layout0: $currlayout"
        while [[ "$newlayout" != "$currlayout" ]]; do
            hyprctl switchxkblayout "$keyb" next
            currlayout=$(hyprctl devices -j | jq -r --arg keyb "$keyb" '.keyboards[] | select(.name==$keyb).active_keymap')
            echo "current layout: $currlayout"
        done
    done
fi

notify-send -u low -i keyboard "Keyboard" "New layout: $newlayout"
