#!/bin/bash

WALLPAPER_FOLDERS=( \
    "$HOME/Imágenes/fondos pantalla/abstract" \
    "$HOME/Imágenes/fondos pantalla/nature"   \
    # "$HOME/Imágenes/fondos pantalla/F1"       \
    "$HOME/Imágenes/BingWallpaper"            \
)

ROFI_THEME="$HOME/.config/rofi/themes/layout-wallpapers.rasi"
WALLPAPER_CONFIG="$HOME/.config/hypr/hyprpaper.conf"

wallpaper_list() {
    for f in "${WALLPAPER_FOLDERS[@]}"; do
        find "$f" -type f
    done
}

current_wallpaper() {
    basename "$(grep path "$WALLPAPER_CONFIG" | cut -d "=" -f 2)"
}

wallpaper_number() {
    echo "$(wallpaper_list)" | grep -n "$(current_wallpaper)" | cut -d ":" -f 1
}

if [ ! -f "$WALLPAPER_CONFIG" ]; then
    cp "${WALLPAPER_CONFIG}.orig" "$WALLPAPER_CONFIG"
fi

case "$1" in
    *random*)
        wallpaper=$(wallpaper_list | shuf -n 1)
        ;;
    *next*)
        line=$(wallpaper_number)
        line=$((line+1))
        wallpaper=$(wallpaper_list | head -n $line | tail -n 1)
        ;;
    *previous*)
        line=$(wallpaper_number)
        line=$((line-1))
        wallpaper=$(wallpaper_list | head -n $line | tail -n 1)
        ;;
    *)
        theme="prompt{enabled:false;} entry{placeholder:\"Elegir fondo de pantalla...\";}"
        wallpaper=$(wallpaper_list \
            | awk -F "" '{print $0 "\0icon\x1f" $0;}' \
            | rofi -dmenu -show-icons -config $ROFI_THEME -theme-str "$theme")
        ;;
esac

if [ -n "$wallpaper" ]; then
    # Cambia la configuración inicial del fondo de pantalla
    sed -i "s#    path.*#    path = $wallpaper#" $WALLPAPER_CONFIG

    # Ejecuta cambio de fondo de pantalla
    $HOME/.config/hypr/scripts/hypr-set-wallpaper "$wallpaper"
    notify-send -u low "Set wallpaper" "$(basename "$wallpaper")"
fi
