#!/bin/bash

# DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function start_vm () {
    state=$(virsh --connect qemu:///system list --all | grep "$1")

    if [[ "$state" =~ "apagado" ]]; then
        virsh --connect qemu:///system start "$1" &
    fi

    GDK_BACKEND=x11 WAYLAND_DISPLAY= virt-viewer --connect=qemu:///system --attach --hotkeys zoom-in=ctrl+alt+shift+f11,zoom-out=ctrl+alt+shift+f12 "$1"
}

start_vm "$1"
