#!/bin/bash

kitty_conf=$HOME/.config/kitty/theme.conf
alacritty_conf=$HOME/.config/alacritty/theme.toml

# figlet -c "Terminal font"

if [ ! -f "$kitty_conf" ]; then
    cp "$kitty_conf".orig "$kitty_conf"
fi

if [ ! -f "$alacritty_conf" ]; then
    cp "$alacritty_conf".orig "$alacritty_conf"
fi

if [ -n "$1" ]; then
    font="$1"
else
    current_font=$(grep ^font_family $kitty_conf | sed 's/^font_family  *//')
    fonts=$(fc-list :spacing=100 -f "%{family[0]}\n" | sort -u | sed 's/\(.*\)/<span font_family="\1">\1<\/span>/')
    font=$(hypr-sys-show-menu "$current_font" "$fonts")
fi

if [[ -n "$font" ]]; then
    if [[ -f $kitty_conf ]]; then
        sed -i "s/^font_family .*/font_family  $font/g" $kitty_conf
        pkill -USR1 kitty
    fi

    if [[ -f $alacritty_conf ]]; then
        sed -i "s/^family = \".*\"/family = \"$font\"/g" $alacritty_conf
    fi
fi

