#!/usr/bin/env bash

OPCIONES=$(
    virsh --connect qemu:///system list --all |
    sed -nE 's/ [-[:digit:]+][ ]*([[:alnum:]_-]*[ ]*[[:alpha:]]*)/\1/p'
)

VM=$(
    printf '%s' "$OPCIONES" |
    rofi -dmenu -p 'Start VM' -no-cycle -theme layout-menu |
    cut -d " " -f 1
)

if [[ -n "$VM" ]]; then
    "$XDG_CONFIG_HOME/hypr/scripts/hypr-start-vm" "$VM"
fi
