#!/bin/bash

TERMINAL=kitty

SCRIPT_PATH="$XDG_CONFIG_HOME/hypr/scripts"
export PATH="$SCRIPT_PATH:$PATH"

SELF=$SCRIPT_PATH/hypr-sys-menu

exec_pgm() {
    coproc ( "$@" > /dev/null )
    exit 0
}

terminal() {
    local cmd="$@"
    exec_pgm $TERMINAL --class hypr-terminal-float --title=Fedora bash -c -- "$cmd"
}

present_terminal() {
    local cmd="$@"
    exec_pgm $TERMINAL --class hypr-terminal-float bash -c -- "hypr-show-logo; $cmd; hypr-show-done"
}

edit_file() {
    notify-send -u low "Editing config file" "$1"
    exec_pgm $TERMINAL nvim "$1"
}

webapp() {
    exec_pgm brave-browser --password-store=basic --new-window --app="$1"
    # exec_pgm flatpak run com.brave.Browser --password-store=basic --new-window --app=$1
}

entry() {
    printf '%s\0info\x1f%s\n' "$1" "$2"
}

title_menu() {
    case "$1" in
        main)              echo "Start" ;;
        style)             echo "Style" ;;
        learn)             echo "Learn" ;;
        trigger)           echo "Trigger" ;;
        capture)           echo "Capture" ;;
        screenshot)        echo "Screenshot" ;;
        toggle)            echo "Toggle" ;;
        power_management)  echo "Power Management" ;;
        setup)             echo "Setup" ;;
        update)            echo "Update" ;;
        system)            echo "System" ;;
    esac
}

show_bar_layouts() {
    local WAYBAR_STYLE="$XDG_CONFIG_HOME/waybar/theme.css"
    local temas=(Square Circle Underscore Mac Float Tahoe KDE)

    local current_layout=$(grep import "$WAYBAR_STYLE" | grep themes | cut -d "/" -f 2)

    for i in "${temas[@]}"; do
        if [ "${i,,}" = "$current_layout" ]; then
            entry "<i>$i</i>"   "act:style_bar_layout:$i"
        else
            entry "$i"   "act:style_bar_layout:$i"
        fi
    done
}

show_theme_colors() {
    local themes_dir"=$XDG_CONFIG_HOME/hypr/themes"
    local state_home=${XDG_STATE_HOME:-$HOME/.local/state}
    local theme_state=$state_home/hypr/theme
    local themes

    mapfile -t themes < <(
        find "$themes_dir" -maxdepth 1 -type f -name '*.toml' -printf '%f\n' |
            sed 's/\.toml$//' | sort
    )
    selected_theme=$(cat "$theme_state" | head -n 1)

    for theme_name in "${themes[@]}"; do
        label=$(sed -E 's/(^|-)([a-z])/\1\U\2/g' <<< "$theme_name")
        if [ "$theme_name" = "$selected_theme" ]; then
            entry "<i>$label</i>"  "act:style_colors:$label"
        else
            entry "$label"  "act:style_colors:$label"
        fi
    done
}

render() {
    local menu="$1"
    local title="$(title_menu "$menu")"

    printf '\0prompt\x1f%s\n' "$title"
    printf '\0no-custom\x1ftrue\n'
    printf '\0markup-rows\x1ftrue\n'
    printf '\0data\x1f%s\n' "$menu"
    # printf '\0theme\x1fentry{placeholder:"%s...";}\n' "$title"

    case "$menu" in
        main)
            entry "󰀻  Apps"     "act:apps"
            entry "  Search"   "act:search"
            entry "  Style"    "menu:style"
            entry "  Learn"    "menu:learn"
            entry "󱓞  Trigger"  "menu:trigger"
            entry "  Setup"    "menu:setup"
            entry "  Update"   "menu:update"
            entry "  About"    "act:about"
            entry "  System"   "menu:system"
            ;;
        style)
            entry "  Bar Layout"           "menu:bar_layout"
            entry "󰸌  Colors"               "menu:theme_colors"
            entry "  Font"                 "act:style_font"
            entry "  Background"           "act:style_background"
            entry "  Random Background"    "act:style_random_bg"
            entry "  Hyprland"             "act:style_hyprland"
            ;;
        bar_layout)
            show_bar_layouts
            ;;
        theme_colors)
            show_theme_colors
            ;;
        learn)
            entry "  Keybindings"  "act:learn_keybindings"
            entry "  Omarchy"      "act:learn_omarchy"
            entry "  Hyprland"     "act:learn_hyprland"
            entry "  Waybar"       "act:learn_waybar"
            entry "  NerdFonts"    "act:learn_nerdfonts"
            entry "󰣇  Arch"         "act:learn_arch"
            entry "  Neovim"       "act:learn_neovim"
            entry "󱆃  Bash"         "act:learn_bash"
            entry "  Tmux"         "act:learn_tmux"
            ;;
        trigger)
            entry "  Capture"  "menu:capture"
            entry "  Toggle"   "menu:toggle"
            ;;
        capture)
            entry "  Screenshot"       "menu:screenshot"
            entry "  Screenrecord"     "menu:screenrecord"
            entry "󰃉  Color"            "act:capture_color"
            ;;
        screenshot)
            entry "󰩬   Region to clipboard"     "act:screenshot_region_clip"
            entry "󰩬   Region to file"          "act:screenshot_region_file"
            entry "󰹑   Display to clipboard"    "menu:capture"
            entry "󰹑   Display to file"         "act:screenshot_display_file"
            ;;
        screenrecord)
            entry "󰩬  Region"   "act:screenrecord_region"
            entry "󰹑  Display"  "act:screenrecord_display"
            ;;
        toggle)
            entry "  Wifi"                     "act:toggle_wifi"
            entry "󰂯  Bluetooth"                "act:toggle_bluetooth"
            entry "  Power Management"         "menu:power_management"
            entry "  Keyboard Layout"          "act:toggle_kb_layout"
            entry "󰪛  Keyboard ControlCaps"     "act:toggle_controlcaps"
            entry "󱄄  Screensaver"              "act:toggle_screensaver"
            entry "󰔎  Nightlight"               "act:toggle_nightlight"
            entry "󱫖  Idle Lock"                "act:toggle_idle"
            entry "󰍜  Top Bar"                  "act:toggle_topbar"
            ;;
        power_management)
            entry "  Balanced"             "act:pm_balanced"
            entry "  Balanced Battery"     "act:pm_balanced_battery"
            entry "  Performance"          "act:pm_performance"
            entry "  Power Saver"          "act:pm_powersaver"
            ;;
        setup)
            entry "  Configs"      "act:setup_configs"
            entry "  Audio"        "act:setup_audio"
            entry "  Wifi"         "act:setup_wifi"
            entry "󰂯  Bluetooth"    "act:setup_bluetooth"
            entry "󰍹  Monitors"     "act:setup_monitors"
            entry "󰐪  Printers"     "act:setup_printers"
            entry "  Keybindings"  "act:setup_keybindings"
            entry "  Input"        "act:setup_input"
            entry "󰈷  Fingerprint"  "act:setup_fingerprint"
            entry "  Fido2"        "act:setup_fido2"
            ;;
        update)
            entry "  Update"               "act:update_run"
            entry "󰉉  Install package"      "act:update_install"
            entry "󰭌  Remove package"       "act:update_remove"
            ;;
        system)
            entry " Lock"          "act:system_lock"
            entry "󰗽 Logout"        "act:system_logout"
            entry " Suspend"       "act:system_suspend"
            entry " Reboot"        "act:system_reboot"
            entry "󰐥 Power Off"     "act:system_poweroff"
            ;;
    esac
}

run_action() {
    case "$1" in
        apps)                   exec_pgm rofi -i -show drun -show-icons -theme layout-apps ;;
        search)                 exec_pgm hypr-search-home ;;
        about)                  terminal "fastfetch; hypr-show-done" ;;

        style_bar_layout*)      exec_pgm hypr-switch-theme "${1#style_bar_layout:}" ;;
        style_colors*)          exec_pgm hypr-switch-colors "${1#style_colors:}" ;;
        style_font)             exec_pgm hypr-switch-font ;;
        style_background)       exec_pgm hypr-switch-wallpaper ;;
        style_random_bg)        exec_pgm hypr-switch-wallpaper random ;;
        style_hyprland)         exec_pgm edit_file "$XDG_CONFIG_HOME/hypr/lua/looknfeel.lua" ;;

        learn_keybindings)      exec_pgm hypr-show-keybinds ;;
        learn_omarchy)          webapp "https://manuals.omamix.org/2/the-omarchy-manual" ;;
        learn_hyprland)         webapp "https://wiki.hypr.land/" ;;
        learn_waybar)           webapp "https://github.com/Alexays/Waybar/wiki" ;;
        learn_nerdfonts)        webapp "https://www.nerdfonts.com/cheat-sheet" ;;
        learn_arch)             webapp "https://wiki.archlinux.org/title/Main_page" ;;
        learn_neovim)           webapp "https://www.lazyvim.org/keymaps" ;;
        learn_bash)             webapp "https://devhints.io/bash" ;;
        learn_tmux)             webapp "https://tmuxcheatsheet.com/" ;;

        capture_color)          exec_pgm hyprpicker -a ;;

        screenshot_region_clip)     exec_pgm hypr-cmd-screenshot clipboard ;;
        screenshot_region_file)     exec_pgm hypr-cmd-screenshot region ;;
        screenshot_display_file)    exec_pgm hypr-cmd-screenshot ;;

        screenrecord_region)    exec_pgm "$OMARCHY_BIN_PATH/omarchy-cmd-screenrecord" ;;
        screenrecord_display)   exec_pgm "$OMARCHY_BIN_PATH/omarchy-cmd-screenrecord" output ;;

        toggle_wifi)            exec_pgm hypr-switch-wifi ;;
        toggle_bluetooth)       exec_pgm hypr-bluetooth --toggle ;;
        toggle_kb_layout)       exec_pgm hypr-switch-keyboard-layout ;;
        toggle_controlcaps)     exec_pgm hypr-switch-controlcaps ;;
        toggle_screensaver)     exec_pgm "$OMARCHY_BIN_PATH/omarchy-launch-screensaver" ;;
        toggle_nightlight)      exec_pgm hypr-switch-nightlight ;;
        toggle_idle)            exec_pgm "$OMARCHY_BIN_PATH/omarchy-toggle-idle" ;;
        toggle_topbar)          exec_pgm pkill -SIGUSR1 waybar ;;

        pm_balanced)            exec_pgm tuned-adm profile balanced ;;
        pm_balanced_battery)    exec_pgm tuned-adm profile balanced-battery ;;
        pm_performance)         exec_pgm tuned-adm profile throughput-performance ;;
        pm_powersaver)          exec_pgm tuned-adm profile powersave ;;

        setup_configs)          exec_pgm hypr-edit-config ;;
        setup_audio)            terminal wiremix ;;
        setup_wifi)             exec_pgm hypr-nmcli-rofi ;;
        setup_bluetooth)        exec_pgm blueman-manager ;;
        setup_monitors)         exec_pgm hypr-switch-monitor ;;
        setup_printers)         webapp "http://localhost:631" ;;
        setup_keybindings)      if [ "$DESKTOP_SESSION" = "bspwm" ]; then
                                    edit_file "$XDG_CONFIG_HOME/sxhkd/sxhkdrc";
                                else
                                    edit_file "$XDG_CONFIG_HOME/hypr/lua/keybinds.lua";
                                fi
                                ;;
        setup_input)            edit_file "$XDG_CONFIG_HOME/hypr/lua/input.lua" ;;
        setup_fingerprint)      terminal "$OMARCHY_BIN_PATH/omarchy-setup-fingerprint" ;;
        setup_fido2)            terminal "$OMARCHY_BIN_PATH/omarchy-setup-fido2" ;;

        update_run)             present_terminal hypr-do-update ;;
        update_install)         terminal "hypr-pkg-install; hypr-show-done" ;;
        update_remove)          terminal "hypr-pkg-remove; hypr-show-done" ;;

        system_lock)            exec_pgm hyprlock ;;
        system_logout)          exec_pgm loginctl terminate-user "$USER" ;;
        system_suspend)         exec_pgm systemctl suspend ;;
        system_reboot)          exec_pgm systemctl reboot ;;
        system_poweroff)        exec_pgm systemctl poweroff ;;
    esac
}

load_rofi() {
    local font="Hack Nerd Font 16"
    local width="22%"
    local theme="entry{placeholder:\"Search...\";} window{width:$width;}"

    rofi -show sysmenu -modes "sysmenu:$SELF" -i -format p -theme-str "$theme" -font "$font"
}

# echo "ROFI_RETV: ${ROFI_RETV}"
# echo "ROFI_DATA: ${ROFI_DATA}"
# echo "ROFI_INFO: ${ROFI_INFO}"

if [ -n "${ROFI_RETV}" ]; then
    # When call the script when rofi window is loaded, must show the options
    if [ "$ROFI_RETV" = "1" ] && [ -n "$ROFI_INFO" ]; then
        case "$ROFI_INFO" in
            menu:*)  render     "${ROFI_INFO#menu:}" ;;
            act:*)   run_action "${ROFI_INFO#act:}"  ;;
        esac
    else
        render "${INI_MENU-main}"
    fi
else
    # When call the script, must load rofi window first
    [ -n "$1" ] && export INI_MENU="$1"
    load_rofi
fi

