#!/bin/bash

waybar_style=$XDG_CONFIG_HOME/waybar/colors.css

current_theme() {
    grep -m1 "THEME:" $waybar_style | sed -E 's/.*THEME:\s*([a-z0-9-]+).*/\1/'
}

if [ -n "$1" ]; then
    theme=$1
else
    temas=(Catppuccin Catppuccin-Latte Dracula Nord Nord-Frost)

    opts=""
    for i in "${temas[@]}"; do
        if [ "${i,,}" = "$(current_theme)" ]; then
            opts="$opts<i>$i</i>\n"
        else
            opts="$opts$i\n"
        fi
    done
    theme=$(hypr-sys-show-menu "Colors" "$opts")
fi

if [ -n "$theme" ]; then
    hypr-generate-themes ${theme,,}
    [ "$DESKTOP_SESSION" = "bspwm" ] && bspc wm --restart
    notify-send -u low "Colors" "Change colors to $theme"
fi

