#!/usr/bin/env bash

set -euo pipefail

WAYBAR_STYLE=$XDG_CONFIG_HOME/waybar/theme.css
WAYBAR_LAYOUT=$XDG_CONFIG_HOME/waybar/theme.jsonc
STYLES_DIR=$XDG_CONFIG_HOME/waybar/themes

create_config_file() {
    if [[ ! -f "$1" ]]; then
        cp "${1}.orig" "$1"
    fi
}

restore_bar() {
    if [[ "$DESKTOP_SESSION" == bspwm ]]; then
        bspc wm --restart;
    else
        "$XDG_CONFIG_HOME/hypr/scripts/hypr-restore-waybar" --silent;
    fi
}

list_styles() {
    find "$STYLES_DIR" -type f -printf '%f\n' | sed 's/\.css//' | sort -u
}

get_style() {
    sed -nE 's|.*themes/(.*).css";|\1|p' "$WAYBAR_STYLE" | head -n 1
}

set_style() {
    local style=$1

    if [[ -n "$style" ]]; then
        sed -i "s|\"themes/.*\"|\"themes/$1.css\"|" "$WAYBAR_STYLE"

        restore_bar
        notify-send -u low -i topmenu-applet "Bar style" "Change style to $style"
    fi

}

get_position() {
    sed -nE 's/[[:space:]]*"position": "(.*)"/\1/p' "$WAYBAR_LAYOUT"
}

set_position() {
    local position=$1
    local stack

    if [ -n "$position" ]; then
        sed -i -E "s/(\"position\"):.*/\1: \"$position\"/" "$WAYBAR_LAYOUT"

        # fixes top/bottom margin in case of floating bar
        stack="$("$XDG_CONFIG_HOME/hypr/scripts/hypr-bar-layout" --get-stack)"
        if [[ $stack == floating ]]; then
            set_stack "$stack"
        fi

        restore_bar
        notify-send -u low -i topmenu-applet "Bar position" "Change bar position to $position"
    fi
}

get_stack() {
    local margin

    margin=$(sed -nE 's/[[:space:]]*margin: (.*);/\1/p' "$WAYBAR_STYLE")

    [[ $margin == 0em ]] && printf 'stacked' || printf 'floating'
}

set_stack() {
    local stacked=$1
    local margin=7
    local position

    if [[ -n "$stacked" ]]; then
        case $stacked in
            stacked)
                sed -i -E 's/([[:space:]]margin): .*;/\1: 0em;/' "$WAYBAR_STYLE"
                ;;
            floating)
                position="$("$XDG_CONFIG_HOME/hypr/scripts/hypr-bar-layout" --get-position)"
                if [[ $position == top ]]; then
                    sed -i -E 's/([[:space:]]margin): .*;/\1: 0.5em 0.5em 0em 0.5em;/' "$WAYBAR_STYLE"
                else
                    sed -i -E 's/([[:space:]]margin): .*;/\1: 0em 0.5em 0.5em 0.5em;/' "$WAYBAR_STYLE"
                fi
                ;;
        esac

        notify-send -u low -i topmenu-applet "Bar stack" "Change bar position to $stacked"
    fi
}

command_help() {
    cat <<USAGE
Uso: hypr-bar-layout [OPCIONES]

    --menu                  Despliega menu de seleccion de estilo de barra
    --list-styles           Despliega listado de estilos disponibles para la barra
    --get-style             Despliega estilo actual de la barra
    --set-style <ESTILO>    Aplica el estilo ESTILO a la barra
    --get-position          Devuelve la posicion de la barra
    --set-position <POS>    Aplica la posicion POS a la barra
    --get-stack             Devuelve si la barra es stacked o flotante
    --set-stack <STACKED>   Aplica el tipo stacked o flotante a la barra

USAGE
}

create_config_file "$WAYBAR_STYLE"
create_config_file "$WAYBAR_LAYOUT"

case "${1:-}" in
    --menu) "$XDG_CONFIG_HOME/hypr/scripts/hypr-sys-menu" --menu style ;;

    list-styles | --list-styles)        list_styles ;;

    get-style | --get-style)            get_style ;;
    set-style | --set-style)            set_style "$2" ;;

    get-position | --get-position)      get_position ;;
    set-position | --set-position)      set_position "$2" ;;

    get-stack | --get-stack)            get_stack ;;
    set-stack | --set-stack)            set_stack "$2" ;;

    *) command_help ;;
esac
