#!/bin/bash

PID=$(pidof waybar)
if [ -n "$PID" ]; then
    notify-send -u low "Waybar" "Reload Waybar"
    pkill -SIGUSR2 waybar
else
    # GTK_THEME=Nordic setsid waybar &
    setsid waybar &
    notify-send -u low "Waybar" "Restore Waybar"
fi
