#!/usr/bin/env bash

function start_vm () {
    local vm="$1"

    state="$(virsh --connect qemu:///system list --all | grep "$vm")"

    if [[ $state =~ apagado ]]; then
        virsh --connect qemu:///system start "$vm" &
    fi

    GDK_BACKEND=x11 WAYLAND_DISPLAY= virt-viewer --connect=qemu:///system --attach --hotkeys zoom-in=ctrl+alt+shift+f11,zoom-out=ctrl+alt+shift+f12 "$vm"
}

start_vm "$1"
