#!/bin/bash

TERMINAL=kitty
SCRIPT_PATH=$XDG_CONFIG_HOME/hypr/scripts
export PATH="$SCRIPT_PATH:$PATH"

menu() {
    hypr-sys-show-menu "$1" "$2"
}

terminal() {
    $TERMINAL --class hypr-sys-menu --title=Fedora bash -c "$1"
}

present_terminal() {
    local cmd="$*"
    $TERMINAL --class hypr-sys-menu bash -c "hypr-show-logo; $cmd; hypr-show-done"
}

edit_file() {
    notify-send -u low "Editing config file" "$1"
    $TERMINAL nvim "$1"
}

back_to() {
    "$1"
}

webapp() {
    brave-browser --password-store=basic --new-window --app=$1
    # flatpak run com.brave.Browser --password-store=basic --new-window --app=$1
}

show_learn_menu() {
    # case $(menu "Learn" "  Keybindings\n  Omarchy\n  Hyprland\n  Bspwm\n  Waybar\n  Polybar\n  NerdFonts\n󰣇  Arch\n  Neovim\n󱆃  Bash") in
    case $(menu "Learn" "  Keybindings\n  Omarchy\n  Hyprland\n  Waybar\n  NerdFonts\n󰣇  Arch\n  Neovim\n󱆃  Bash") in
        *Keybindings*) hypr-show-keybinds ;;
        *Omarchy*)     webapp "https://manuals.omamix.org/2/the-omarchy-manual" ;;
        *Hyprland*)    webapp "https://wiki.hypr.land/" ;;
        *Bspwm*)       webapp "https://github.com/baskerville/bspwm/wiki" ;;
        *Waybar*)      webapp "https://github.com/Alexays/Waybar/wiki" ;;
        *Polybar*)     webapp "https://github.com/polybar/polybar/wiki" ;;
        *NerdFonts*)   webapp "https://www.nerdfonts.com/cheat-sheet" ;;
        *Arch*)        webapp "https://wiki.archlinux.org/title/Main_page" ;;
        *Bash*)        webapp "https://devhints.io/bash" ;;
        *Neovim*)      webapp "https://www.lazyvim.org/keymaps" ;;
        *) show_main_menu ;;
    esac
}

show_trigger_menu() {
    case "$(menu "Trigger" "  Capture\n  Toggle")" in
        *Capture*) show_capture_menu ;;
        *Toggle*)  show_toggle_menu ;;
        *) show_main_menu ;;
    esac
}

show_capture_menu() {
    case $(menu "Capture" "  Screenshot\n  Screenrecord\n󰃉  Color") in
        *Screenshot*)   show_screenshot_menu ;;
        *Screenrecord*) show_screenrecord_menu ;;
        *Color*)        pkill hyprpicker || hyprpicker -a ;;
        *) back_to show_trigger_menu ;;
    esac
}

show_screenshot_menu() {
    case $(menu "Screenshot" "󰩬   Region to clipboard\n󰩬   Region to file\n󰹑    Display to clipboard\n󰹑    Display to file") in
        *Region\ to\ clipboard*) hypr-cmd-screenshot clipboard ;;
        *Region\ to\ file*)      hypr-cmd-screenshot region ;;
        *Display\ to\ file*)     hypr-cmd-screenshot ;;
        *) show_capture_menu ;;
    esac
}

show_screenrecord_menu() {
    case $(menu "Screenrecord" "󰩬  Region\n󰹑  Display") in
        *Region*)  $OMARCHY_BIN_PATH/omarchy-cmd-screenrecord ;;
        *Display*) $OMARCHY_BIN_PATH/omarchy-cmd-screenrecord output ;;
        *) show_capture_menu ;;
    esac
}

show_toggle_menu() {
    # wifi_status=$(nmcli radio wifi)
    # bt_status=$(if $(bluetoothctl show | grep -q "Powered: no" > /dev/null ); then echo "disabled"; else echo "enabled"; fi)
    # power_status=$(tuned-adm active | cut -d " " -f 4)
    # keyb_status=$(setxkbmap -query | grep layout | awk '{print $2}')
    case $(menu "Toggle" "  Wifi\n󰂯  Bluetooth\n  Power Management\n  Keyboard Layout\n󰪛  Keyboard ControlCaps\n󱄄  Screensaver\n󰔎  Nightlight\n󱫖  Idle Lock\n󰍜  Top Bar") in
        *Wifi*)                  hypr-switch-wifi ;;
        *Bluetooth*)             hypr-bluetooth --toggle ;;
        *Power\ Management*)     show_power_management ;;
        *Keyboard\ Layout*)      hypr-switch-keyboard-layout ;;
        *Keyboard\ ControlCaps*) hypr-switch-controlcaps ;;
        *Nightlight*)            hypr-switch-nightlight ;;
        *Bar*)                   pkill -SIGUSR1 waybar ;;
        *Screensaver*)       $OMARCHY_BIN_PATH/omarchy-launch-screensaver ;;
        *Idle*)              $OMARCHY_BIN_PATH/omarchy-toggle-idle ;;
        *) back_to show_trigger_menu ;;
    esac
}

show_power_management() {
    case $(menu "Power Management" "  Balanced\n  Balanced Battery\n  Performance\n  Power Saver") in
        *Balanced\ Battery*) tuned-adm profile balanced-battery ;;
        *Balanced*)          tuned-adm profile balanced ;;
        *Performance*)       tuned-adm profile throughput-performance ;;
        *Power\ Saver*)      tuned-adm profile powersave ;;
        *) back_to show_toggle_menu ;;
    esac
}

show_style_menu() {
    case $(menu "Style" "  Bar Layout\n󰸌  Colors\n  Font\n  Background\n  Random Background\n  Hyprland") in
        *Bar\ Layout*)         hypr-switch-theme ;;
        *Colors*)              hypr-switch-colors ;;
        *Font*)                hypr-switch-font ;;
        *Random\ Background*)  hypr-switch-wallpaper random ;;
        *Background*)          hypr-switch-wallpaper ;;
        *Hyprland*)            edit_file $XDG_CONFIG_HOME/hypr/lua/looknfeel.lua ;;
        *) show_main_menu ;;
    esac
}

show_setup_menu() {
    case $(menu "Setup" "  Configs\n  Audio\n  Wifi\n󰂯  Bluetooth\n󰍹  Monitors\n󰐪  Printers\n  Keybindings\n  Input\n󰈷  Fingerprint\n  Fido2") in
        *Configs*)      hypr-edit-config ;;
        *Audio*)        terminal wiremix ;;
        *Wifi*)         hypr-nmcli-rofi ;;
        *Bluetooth*)    blueman-manager ;;
        *Monitors*)     hypr-switch-monitor ;;
        *Printers*)     webapp "http://localhost:631" ;;
        *Keybindings*)  [ $DESKTOP_SESSION = "bspwm" ] && edit_file $XDG_CONFIG_HOME/sxhkd/sxhkdrc || edit_file $XDG_CONFIG_HOME/hypr/lua/keybinds.lua ;;
        *Input*)        edit_file $XDG_CONFIG_HOME/hypr/lua/input.lua ;;
        *Fingerprint*)  terminal $OMARCHY_BIN_PATH/omarchy-setup-fingerprint ;;
        *Fido2*)        terminal $OMARCHY_BIN_PATH/omarchy-setup-fido2 ;;
        *) show_main_menu ;;
    esac
}

show_update_menu() {
    case $(menu "Update" "  Update\n󰉉  Install package\n󰭌  Remove package") in
        *Update*)   present_terminal hypr-do-update ;;
        *Install*)  terminal "hypr-pkg-install; hypr-show-done" ;;
        *Remove*)   terminal "hypr-pkg-remove; hypr-show-done" ;;
        *) show_main_menu ;;
    esac
}

show_system_menu() {
    case $(menu "System" " Lock\n󰗽 Logout\n󰐥 Power Off\n Suspend\n Restart") in
        *Lock*)        hyprlock ;;
        *Logout*)      loginctl terminate-user $USER ;;
        *Power\ Off*)  systemctl poweroff ;;
        *Suspend*)     systemctl suspend ;;
        *Restart*)     systemctl reboot ;;
        *) show_main_menu ;;
    esac
}

show_main_menu() {
    go_to_menu "$(menu "Start" "󰀻  Apps\n  Search\n  Style\n  Learn\n󱓞  Trigger\n  Setup\n  Update\n  About\n  System")"
}

go_to_menu() {
    case "${1,,}" in
        *apps*)       rofi -i -show drun -show-icons -theme layout-apps;;
        *search*)     hypr-search-home ;;
        *learn*)      show_learn_menu ;;
        *trigger*)    show_trigger_menu ;;
        *capture*)    show_capture_menu ;;
        *toggle*)     show_toggle_menu ;;
        *style*)      show_style_menu ;;
        *setup*)      show_setup_menu ;;
        *do-update*)  present_terminal hypr-do-update ;;
        *update*)     show_update_menu ;;
        *about*)      terminal "fastfetch && read -n 1 -s" ;;
        *system*)     show_system_menu ;;
    esac
}

if [ -n "$1" ]; then
    go_to_menu "$1"
else
    show_main_menu
fi
