#!/usr/bin/env bash

HYPRCONF="conf"
[ -f "$XDG_CONFIG_HOME/hypr/hyprland.lua" ] && HYPRCONF="lua"

if hyprctl getoption input:kb_options | grep -q swapcaps; then
    case $HYPRCONF in
        *conf*) hyprctl keyword input:kb_options ctrl: ;;
        *lua*)  hyprctl eval "hl.config({ input = { kb_options = 'ctrl:' } })" ;;
    esac
else
    case $HYPRCONF in
        *conf*) hyprctl keyword input:kb_options ctrl:swapcaps ;;
        *lua*)  hyprctl eval "hl.config({ input = { kb_options = 'ctrl:swapcaps' } })" ;;
    esac
fi
