#!/bin/bash

wallpaper="/home/daniel/Imágenes/fondos pantalla/abstract/liquid/fluidic-glossy-gradient-background-purple-background-3840x2160-7641.jpg"

if [ -n "$1" ]; then
    wallpaper="$1"
fi

hyprctl hyprpaper wallpaper "eDP-1,$wallpaper"
