#!/bin/bash

waybar_style=$XDG_CONFIG_HOME/waybar/theme.css
waybar_layout=$XDG_CONFIG_HOME/waybar/theme.jsonc

current_theme() {
    grep import $waybar_style | grep themes | cut -d "/" -f 2
}

change_theme() {
    # waybar
    sed -i "s/\".*\/style.css\"/\"themes\/$1\/style.css\"/" $waybar_style
    sed -i "s/\".*\/layout.jsonc\"/\"\$HOME\/\.config\/waybar\/themes\/$1\/layout.jsonc\"/" $waybar_layout
}

create_config_file() {
    if [ ! -f "$1" ]; then
        cp "${1}.orig" "$1"
    fi
}

create_config_file "$waybar_style"
create_config_file "$waybar_layout"


if [ -n "$1" ]; then
    theme=$1
else
    temas=(Square Circle Underscore Mac Float Tahoe KDE)

    opts=""
    for i in "${temas[@]}"; do
        if [ "${i,,}" = "$(current_theme)" ]; then
            opts="$opts<i>$i</i>\n"
        else
            opts="$opts$i\n"
        fi
    done

    theme=$(hypr-sys-show-menu "Bar Layout" "$opts")
fi

if [ -n "$theme" ]; then
    change_theme ${theme,,}
    [ "$DESKTOP_SESSION" = "bspwm" ] && bspc wm --restart || $HOME/.config/hypr/scripts/hypr-restore-waybar
    notify-send -u low "Theme" "Change theme to $theme"
fi

