#!/bin/bash

[[ $1 == "up" ]] && step="10%+" || step="10%-"

if [[ -n "$step" ]]; then
    brightnessctl s "$step"
    brightness="$(brightnessctl -P g)"

    notify-send -c OSD -h int:value:"$brightness" -i display-brightness-symbolic '' "Brillo pantalla ($brightness%)"
fi
