#!/bin/sh

HYPRCONF="conf"
[ -f $HOME/.config/hypr/hyprland.lua ] && HYPRCONF="lua"

if [[ -n "$(hyprctl getoption input:kb_options | grep swapcaps)" ]]; then
    case $HYPRCONF in
        *conf*) hyprctl keyword input:kb_options ctrl: ;;
        *lua*)  hyprctl eval "hl.config({ input = { kb_options = 'ctrl:' } })" ;;
    esac
else
    case $HYPRCONF in
        *conf*) hyprctl keyword input:kb_options ctrl:swapcaps ;;
        *lua*)  hyprctl eval "hl.config({ input = { kb_options = 'ctrl:swapcaps' } })" ;;
    esac
fi
