#!/usr/bin/env bash

bluetooth_state() {
    bluetoothctl show | grep -q "Powered: no" && printf 'off' || printf 'on'
}

bluetooth_print() {
    if [[ "$(bluetooth_state)" == off ]]; then
        printf '%%{F#66FFFFFF}'
    else
        if bluetoothctl info | grep -q 'Device '; then
            printf ''
        else
            printf ''
        fi
    fi
}

bluetooth_toggle() {
    if [[ "$(bluetooth_state)" == off ]]; then
        # printf 'Encendiendo bluetooth\n'
        bluetoothctl power on >> /dev/null
    else
        # Desconecta los dispositivos pareados
        while read -r _ device name; do
            printf 'Desconectando device: %s (%s)\n' "$name" "$device"
            bluetoothctl disconnect "$device" >> /dev/null
        done < <(bluetoothctl devices Connected | grep Device)

        bluetoothctl power off >> /dev/null
        # printf 'Apagando bluetooth\n'
    fi

    notify-send -u low -i bluetooth "Bluetooth" "Set bluetooth $(bluetooth_state)"
}

case "$1" in
    --toggle) bluetooth_toggle ;;
    --state)  bluetooth_state ;;
    *)        bluetooth_print ;;
esac
