#!/bin/bash

chk_cmd=$(hyprctl eval "onlyWindowMarginRule:is_enabled()")

echo $chk_cmd

# if [ $option -eq 1 ]; then
#     hyprctl keyword master:no_gaps_when_only 0
# else
#     hyprctl keyword master:no_gaps_when_only 1
# fi


