#!/bin/bash

export PATH="$XDG_CONFIG_HOME/hypr/scripts:$PATH"

kitty_conf=$XDG_CONFIG_HOME/kitty/theme.conf
alacritty_conf=$XDG_CONFIG_HOME/alacritty/theme.toml

# figlet -c "Terminal font"

get_fonts() {
    fc-list :spacing=100 -f "%{family[0]}\n" | sort -u
}

if [ ! -f "$kitty_conf" ]; then
    cp "$kitty_conf".orig "$kitty_conf"
fi

if [ ! -f "$alacritty_conf" ]; then
    cp "$alacritty_conf".orig "$alacritty_conf"
fi

if [ -n "$1" ]; then
    font="$1"
else
    current_font=$(grep ^font_family "$kitty_conf" | sed 's/^font_family  *//')
    fonts=$(get_fonts | sed 's/\(.*\)/<span font_family="\1">\1<\/span>/')
    font=$(hypr-sys-show-menu "$current_font" "$fonts")
fi

if [[ -n "$font" ]]; then
    # valida que $font sea una fuenta válida instalada
    if ! get_fonts | grep -q "$font"; then
        printf "%s\n" "ERROR: missing font: $font"
        notify-send "Font" "ERROR: missing font: $font"
        exit 1
    fi

    if [[ -f $kitty_conf ]]; then
        sed -i "s/^font_family .*/font_family  $font/g" "$kitty_conf"
        pkill -USR1 kitty
    fi

    if [[ -f $alacritty_conf ]]; then
        sed -i "s/^family = \".*\"/family = \"$font\"/g" "$alacritty_conf"
    fi
fi

