#!/bin/bash

$XDG_CONFIG_HOME/hypr/scripts/hypr-show-title "Update system packages..."
# figlet -c "Update"

update_flatpak() {
    echo -e "\n\e[32mUpdating flatpak packages...\e[0m"
    flatpak update
}

log_installed_pkgs() {
    dnf list --installed | sort > $installed_file
    echo -e "\n\nFlatpak" >> $installed_file
    flatpak list >> $installed_file
}

installed_file=$HOME/installed_pkg.txt
os=$(grep ^NAME= /etc/os-release | cut -d = -f 2 | tr -d '"')

case ${os,,} in
    *cachyos*)
        sudo pacman -Ssy
        update_flatpak
        log_installed_pkgs
        ;;
    *fedora*)
        sudo dnf upgrade
        update_flatpak
        log_installed_pkgs
        ;;
    *) echo No linux distro detected ;;
esac

# Reload update indicator after updating system
case  "$DESKTOP_SESSION" in
    bspwm) bspc wm --restart ;;
    *)     pkill -RTMIN+7 waybar ;;
esac

