#!/usr/bin/env bash

set -euo pipefail

current_layout() {
    local keyboard=$1

    if [ "$DESKTOP_SESSION" = "bspwm" ]; then
        setxkbmap -query | grep layout | awk '{print $2}'
    else
        hyprctl devices -j | jq -r --arg keyb "$keyboard" '.keyboards[] | select(.name==$keyb).active_keymap'
    fi
}

notify() {
    local mesg=$1

    notify-send -u low -i keyboard "Keyboard" "$mesg"
}

bspwm_next() {
    local newlayout

    if [[ "$(current_layout)" == us ]]; then
        setxkbmap latam
    else
        setxkbmap us
    fi
    newlayout="$(current_layout)"
    notify "New layout: $newlayout"
}

hypr_next() {
    local newlayout currlayout keyboards keyb
    local internal=at-translated-set-2-keyboard
    local external=keychron

    hyprctl switchxkblayout $internal next >/dev/null

    newlayout="$(current_layout "$internal")"
    echo "new internal layout: $newlayout"

    keyboards="$(hyprctl devices -j | jq -r '.keyboards[].name' | grep $external)"
    echo "keyboards: $keyboards"

    for keyb in $keyboards; do
        echo "external: $keyb"
        currlayout="xxx"
        echo "current layout0: $currlayout"
        while [[ "$newlayout" != "$currlayout" ]]; do
            hyprctl switchxkblayout "$keyb" next
            currlayout="$(current_layout "$keyb")"
            echo "current layout: $currlayout"
        done
    done

    notify "New layout: $newlayout"
}


main() {
    if [ "$DESKTOP_SESSION" = "bspwm" ]; then
        bspwm_next
    else
        hypr_next
    fi
}

main "$@"
