#! /bin/bash

abstract_folder="$HOME/Imágenes/fondos pantalla/abstract"
nature_folder="$HOME/Imágenes/fondos pantalla/nature"
bing_folder="$HOME/Imágenes/BingWallpaper"

rofi_theme="$HOME/.config/rofi/themes/layout-wallpapers.rasi"
wallpaper_conf="$HOME/.config/hypr/scripts/hypr-set-wallpaper"


wallpaper=$(find "$abstract_folder" "$nature_folder" -type f \
    | awk -F "" '{print $0 "\0icon\x1f" $0;}' \
    | rofi -dmenu -show-icons -p 󰸉  -config $rofi_theme -theme-str "entry{placeholder:\"Fondo de pantalla...\";}")

# echo "$wallpaper"

if [ -n "$wallpaper" ]; then
    # Cambia la configuración inicial del fondo de pantalla
    sed -i "s#^wallpaper=.*#wallpaper=\"$wallpaper\"#g" $wallpaper_conf

    # Ejecuta cambio de fondo de pantalla
    $HOME/.config/hypr/scripts/hypr-set-wallpaper
fi
