#!/usr/bin/env bash

if [ "$(nmcli radio wifi)" == "enabled" ]; then
    nmcli radio wifi off
    notify-send -u low -i network-wireless "WIFI" "Disable wifi"
else
    nmcli radio wifi on
    notify-send -u low -i network-wireless "WIFI" "Enable wifi"
fi
