#!/bin/bash

WALLPAPER_FOLDERS=( \
    "$HOME/Imágenes/fondos pantalla/abstract" \
    "$HOME/Imágenes/fondos pantalla/nature"   \
    # "$HOME/Imágenes/fondos pantalla/F1"       \
    "$HOME/Imágenes/BingWallpaper"            \
)

ROFI_THEME="$XDG_CONFIG_HOME/rofi/themes/layout-wallpapers.rasi"
WALLPAPER_CONFIG="$XDG_CONFIG_HOME/hypr/hyprpaper.conf"

wallpaper_list() {
    for f in "${WALLPAPER_FOLDERS[@]}"; do
        find "$f" -type f
    done
}

current_wallpaper() {
    basename "$(grep path "$WALLPAPER_CONFIG" | cut -d "=" -f 2)"
}

wallpaper_number() {
    echo "$(wallpaper_list)" | grep -n "$(current_wallpaper)" | cut -d ":" -f 1
}

if [ ! -f "$WALLPAPER_CONFIG" ]; then
    cp "${WALLPAPER_CONFIG}.orig" "$WALLPAPER_CONFIG"
fi

case "${1,,}" in
    *random*)
        wallpaper=$(wallpaper_list | shuf -n 1)
        ;;
    *next*)
        line=$(wallpaper_number)
        line=$((line+1))
        wallpaper=$(wallpaper_list | head -n $line | tail -n 1)
        ;;
    *previous*)
        line=$(wallpaper_number)
        line=$((line-1))
        wallpaper=$(wallpaper_list | head -n $line | tail -n 1)
        ;;
    *)
        theme="prompt{enabled:false;} entry{placeholder:\"Elegir fondo de pantalla...\";}"
        wallpaper=$(wallpaper_list \
            | sed 's|\(.*\)|\1\x00icon\x1f\1|' \
            | rofi -dmenu -show-icons -config $ROFI_THEME -theme-str "$theme")
        ;;
esac

if [ -n "$wallpaper" ]; then
    $XDG_CONFIG_HOME/hypr/scripts/hypr-set-wallpaper "$wallpaper"
fi
