#!/bin/bash

step=""
if [ "$1" = "up" ]; then
    step="10%+"
elif [ "$1" = "down" ]; then
    step="10%-"
fi

if [ -n "$step" ]; then
    brightnessctl s $step
    brightness=$(brightnessctl -P g)
    notify-send -c OSD -h int:value:$brightness -i display-brightness-symbolic "" "Brillo pantalla ($brightness%)"
fi
