#!/usr/bin/env bash

SILENT="${1:-}"
action='Reload'

PID=$(pidof waybar)

if [ -n "$PID" ]; then
    pkill -SIGUSR2 waybar
else
    # GTK_THEME=Nordic setsid waybar &
    setsid waybar &
    action='Restore'
fi

if [[ $SILENT != silent && $SILENT != --silent ]]; then
    notify-send -u low -i reload "Waybar" "$action Waybar"
fi
