#!/usr/bin/env bash

os="$(sed -n 's/^NAME="\(.*\)"/\1/p' /etc/os-release)"

case ${os,,} in
    fedora*) updates=$(dnf check-update -q | grep -Ec ' updates$') ;;
    ubuntu*) updates=$(apt list --upgradable 2> /dev/null | grep -v "Listando" | grep -v -e "^$" | cut -d " " -f 1 | wc -l) ;;
    *)       echo Error: No linux distro detected ;;
esac

if [[ $updates -gt 0 ]]; then
    case $DESKTOP_SESSION in
        bspwm) printf ' (%s)' "$updates" ;;
        *)     printf '{"text": " %s", "tooltip": "%s actualizaciones disponibles"}' "$updates" "$updates" ;;
    esac
else
    case $DESKTOP_SESSION in
        bspwm) printf '' ;;
        *)     printf '{"text": "", "tooltip": ""}' ;;
    esac
fi
