#!/bin/bash

WAYBAR_STYLE=$XDG_CONFIG_HOME/waybar/theme.css
WAYBAR_LAYOUT=$XDG_CONFIG_HOME/waybar/theme.jsonc

current_theme() {
    grep import "$WAYBAR_STYLE" | grep themes | cut -d "/" -f 2
}

change_theme() {
    # waybar
    sed -i "s/\".*\/style.css\"/\"themes\/$1\/style.css\"/" "$WAYBAR_STYLE"
    sed -i "s/\".*\/layout.jsonc\"/\"\$HOME\/\.config\/waybar\/themes\/$1\/layout.jsonc\"/" "$WAYBAR_LAYOUT"
}

create_config_file() {
    if [ ! -f "$1" ]; then
        cp "${1}.orig" "$1"
    fi
}

create_config_file "$WAYBAR_STYLE"
create_config_file "$WAYBAR_LAYOUT"


if [ -n "$1" ]; then
    theme=$1
else
    temas=(Square Circle Underscore Mac Float Tahoe KDE)

    opts=""
    for i in "${temas[@]}"; do
        if [ "${i,,}" = "$(current_theme)" ]; then
            opts="$opts<i>$i</i>\n"
        else
            opts="$opts$i\n"
        fi
    done

    theme=$(hypr-sys-show-menu "Bar Layout" "$opts")
fi

if [ -n "$theme" ]; then
    change_theme "${theme,,}"
    if [ "$DESKTOP_SESSION" = "bspwm" ]; then bspc wm --restart; else "$XDG_CONFIG_HOME/hypr/scripts/hypr-restore-waybar"; fi
    notify-send -u low "Theme" "Change theme to $theme"
fi

