#!/bin/bash

set -euo pipefail

WAYBAR_STYLE=$XDG_CONFIG_HOME/waybar/theme.css
WAYBAR_LAYOUT=$XDG_CONFIG_HOME/waybar/theme.jsonc
STYLES_DIR=$XDG_CONFIG_HOME/waybar/themes

create_config_file() {
    if [ ! -f "$1" ]; then
        cp "${1}.orig" "$1"
    fi
}

restore_bar() {
    if [ "$DESKTOP_SESSION" = "bspwm" ]; then
        bspc wm --restart;
    else
        "$XDG_CONFIG_HOME/hypr/scripts/hypr-restore-waybar" --silent;
    fi
}

fix_float_margin() {
    local position=$1

    if [[ $position == top ]]; then
        echo "top"
        sed -i "s/\"margin-bottom\":.*/\"margin-bottom\": 0/" "$WAYBAR_LAYOUT"
    else
        echo "bottom"
        sed -i "s/\"margin-top\":.*/\"margin-top\": 0,/" "$WAYBAR_LAYOUT"
    fi
}

list_styles() {
    find "$STYLES_DIR" -type f -printf '%f\n' | sed 's/\.css//' | sort -u
}

get_style() {
    sed -nE 's|.*themes/(.*).css";|\1|p' "$WAYBAR_STYLE" | head -n 1
}

set_style() {
    local style=$1

    if [ -n "$style" ]; then
        sed -i "s|\"themes/.*\"|\"themes/$1.css\"|" "$WAYBAR_STYLE"

        restore_bar
        notify-send -u low "Bar style" "Change style to $style"
    fi

}

get_position() {
    sed -nE 's/[[:space:]]*"position": "(.*)",/\1/p' "$WAYBAR_LAYOUT"
}

set_position() {
    local position=$1
    local stack

    if [ -n "$position" ]; then
        sed -i "s/\"position\":.*/\"position\": \"$position\",/" "$WAYBAR_LAYOUT"

        # fixes top/bottom margin in case of floating bar
        stack="$("$XDG_CONFIG_HOME/hypr/scripts/hypr-switch-bar-layout" --get-stack)"
        if [[ $stack == floating ]]; then
            set_stack "$stack"
            fix_float_margin "$position" "$stack"
        fi

        restore_bar
        notify-send -u low "Bar position" "Change bar position to $position"
    fi
}

get_stack() {
    local margin

    margin=$(sed -nE 's/[[:space:]]*"margin-left": (.*),/\1/p' "$WAYBAR_LAYOUT")

    [[ $margin == 0 ]] && printf 'stacked' || printf 'floating'
}

set_stack() {
    local stacked=$1
    local margin=7
    local position margin_top margin_bottom

    if [ -n "$stacked" ]; then
        case $stacked in
            stacked)
                sed -i "s/\"margin-top\":.*/\"margin-top\": 0,/" "$WAYBAR_LAYOUT"
                sed -i "s/\"margin-left\":.*/\"margin-left\": 0,/" "$WAYBAR_LAYOUT"
                sed -i "s/\"margin-right\":.*/\"margin-right\": 0,/" "$WAYBAR_LAYOUT"
                sed -i "s/\"margin-bottom\":.*/\"margin-bottom\": 0/" "$WAYBAR_LAYOUT"
                ;;
            floating)
                sed -i "s/\"margin-left\":.*/\"margin-left\": $margin,/" "$WAYBAR_LAYOUT"
                sed -i "s/\"margin-right\":.*/\"margin-right\": $margin,/" "$WAYBAR_LAYOUT"

                position="$("$XDG_CONFIG_HOME/hypr/scripts/hypr-switch-bar-layout" --get-position)"
                if [[ $position == top ]]; then
                    margin_top=$margin
                    margin_bottom=0
                else
                    margin_top=0
                    margin_bottom=$margin
                fi

                sed -i "s/\"margin-top\":.*/\"margin-top\": $margin_top,/" "$WAYBAR_LAYOUT"
                sed -i "s/\"margin-bottom\":.*/\"margin-bottom\": $margin_bottom/" "$WAYBAR_LAYOUT"
                ;;
        esac

        fix_float_margin "$("$XDG_CONFIG_HOME/hypr/scripts/hypr-switch-bar-layout" --get-position)" "$stacked"

        restore_bar
        notify-send -u low "Bar stack" "Change bar position to $stacked"
    fi
}

create_config_file "$WAYBAR_STYLE"
create_config_file "$WAYBAR_LAYOUT"

if [ -z "${1:-}" ]; then
    "$XDG_CONFIG_HOME/hypr/scripts/hypr-sys-menu" "style"
else
    case "$1" in
        list-styles | --list-styles)    list_styles ;;

        get-style | --get-style)        get_style ;;
        set-style | --set-style)        set_style "$2" ;;

        get-position | --get-position)  get_position ;;
        set-position | --set-position)  set_position "$2" ;;

        get-stack | --get-stack)        get_stack ;;
        set-stack | --set-stack)        set_stack "$2" ;;
    esac
fi
