#!/bin/bash

wallpaper="/home/daniel/Imágenes/fondos pantalla/nature/20230814-GeckoLeaf_ROW1753443584_UHD.jpg"

if [ -n "$1" ]; then
    wallpaper="$1"
fi

pid=$(pidof swaybg)
if [ -n "$pid" ]; then
    killall swaybg
fi

swaybg -i "$wallpaper" -m fill &
