#!/bin/bash

waybar_style=$HOME/.config/waybar/style.css
hypr_conf=$HOME/.config/hypr/conf/theme.conf
hypr_lua=$HOME/.config/hypr/lua/theme.lua
rofi_colors=$HOME/.config/rofi/themes/colors.rasi

if [ ! -f "$waybar_style" ]; then
    cp "$waybar_style".orig "$waybar_style"
fi

if [ ! -f "$hypr_conf" ]; then
    cp "$hypr_conf".orig "$hypr_conf"
fi

if [ ! -f "$hypr_lua" ]; then
    cp "$hypr_lua".orig "$hypr_lua"
fi

if [ ! -f "$rofi_colors" ]; then
    cp "$rofi_colors".orig "$rofi_colors"
fi


current_theme() {
    grep import $waybar_style | grep colors | tr -d '"' | tr -d ';' | cut -d / -f 2 | cut -d . -f 1
}

change_theme() {
    # waybar
    sed -i "s/\"colors\/.*\.css\"/\"colors\/$1.css\"/" $waybar_style

    # hyprland
    sed -i "s/\$theme = .*/\$theme = $1/" $hypr_conf
    sed -i "s/HYPR\.theme_name.*/HYPR.theme_name = \"$1\"/" $hypr_lua

    # rofi
    sed -i "s/^@import \"themes\/colors\/.*\.rasi\"/@import \"themes\/colors\/$1.rasi\"/" $rofi_colors

    # bspwm
    # sed -i "s/^source \$HOME\/\.config\/bspwm\/themes\/.*/source \$HOME\/.config\/bspwm\/themes\/$1/" $HOME/.config/bspwm/bspwmrc

    # polybar
    # sed -i "s/include-file = .*\/config.ini/include-file = \$HOME\/\.config\/polybar\/themes\/$1\/config.ini/" $HOME/.config/polybar/config.ini

}

if [ -n "$1" ]; then
    theme=$1
else
    temas=(Catppuccin Catppuccin-Latte Dracula Nord Nord-Frost)

    opts=""
    for i in "${temas[@]}"; do
        if [ "${i,,}" = "$(current_theme)" ]; then
            opts="$opts<i>$i</i>\n"
        else
            opts="$opts$i\n"
        fi
    done
    theme=$(echo -e $opts | rofi -dmenu -markup-rows -i -format p -p "")
fi

if [ -n "$theme" ]; then
    change_theme ${theme,,}
    [ "$DESKTOP_SESSION" = "bspwm" ] && bspc wm --restart || $HOME/.config/hypr/scripts/hypr-restore-waybar
    notify-send -u low "Colors" "Change colors to $theme"
fi

