#!/usr/bin/env bash

set -euo pipefail

declare -A OPTIONS=(
    [SET_MAIN]='   Solo pantalla de PC'
    [SET_DUP]='   Duplicado'
    [SET_EXT]='  󰍹  Ampliar'
    [SET_SEC]='󰍹   Solo segunda pantalla'
    [SET_OFF]='    Desactivar monitor'
    [SET_ON]='    Activar monitor'
    [SET_RESOL]='󰹑    Cambiar resolucion'
    [SCALE_100]='    Escalar al 100'
    [SCALE_125]='    Escalar al 125'
    [SCALE_133]='    Escalar al 133'
    [SCALE_150]='    Escalar al 150'
    [SCALE_200]='    Escalar al 200'
)

declare -a OPTIONS_ONE_MONITOR=(
    "${OPTIONS[SET_RESOL]}"
    "${OPTIONS[SCALE_100]}"
    "${OPTIONS[SCALE_125]}"
    "${OPTIONS[SCALE_133]}"
    "${OPTIONS[SCALE_150]}"
    "${OPTIONS[SCALE_200]}"
)

declare -a OPTIONS_MULTIPLE_MONITORS=(
    "${OPTIONS[SET_MAIN]}"
    "${OPTIONS[SET_DUP]}"
    "${OPTIONS[SET_EXT]}"
    "${OPTIONS[SET_SEC]}"
)

die() {
    printf 'ERROR: %s\n' "$*" >&2
    notify-send -u critical -t 0 -i dialog-warning 'ERROR: hypr-switch-monitor' "$*"
    exit 1
}

debug() {
    [[ ${HYPR_SWITCH_MONITOR_DEBUG:-false} == true ]] || return 0
    printf 'DEBUG: %s\n' "$*" >&2
}

menu() {
    local options=$1
    local prompt=$2
    local message=${3:-}

    if [[ -n "$message" ]]; then
        printf '%s' "$options" | rofi -a 0:2 -dmenu -p "$prompt" -mesg "$message"
    else
        printf '%s' "$options" | rofi -dmenu -p "$prompt"
    fi
}

notify() {
    local message=$1

    notify-send -u low 'Pantalla' "$message"
}

hyprland_monitors() {
    hyprctl -j monitors all
}

count_monitors() {
    case $BACKEND in
        wayland)  hyprland_monitors | jq -r 'length' ;;
        x11)      xrandr -q | grep -c ' connected' ;;
    esac
}

count_enabled_monitors() {
    case $BACKEND in
        wayland)  hyprland_monitors | jq -r '[.[] | select(.disabled == false)] | length' ;;
        x11)      xrandr -q | grep -c ' connected' ;;
    esac
}

list_monitors() {
    case $BACKEND in
        wayland)  hyprland_monitors | jq -r '.[].name' ;;
        x11)      xrandr -q | awk '$2 == "connected" { print $1 }' ;;
    esac
}

get_monitor_list() {
    local data description icon

    case $BACKEND in
        wayland)
            for monitor in $(list_monitors); do
                data="$(get_monitor_data "$monitor")"
                description="$(get_monitor_property "$data" description)"

                [[ $monitor == "$MON_INT" ]] && icon='' || icon='󰍹'

                printf '%s    %s %s\n' "$icon" "$monitor" "$description"
            done
            ;;
        x11)
            xrandr -q | grep ' connected' | cut -d " " -f 1
            ;;
    esac
}

get_monitor_data() {
    local monitor=$1

    case $BACKEND in
        wayland)
            hyprland_monitors | jq -r --arg monitor "$monitor" '
                .[] | select(.name == $monitor)
                | ["\(.width)x\(.height)", "\(.x)x\(.y)", .description, (.scale | tostring), (.disabled | tostring)]
                | @tsv'
            ;;

        x11)
            printf '%s\t%s\t%s\t%s\t%s' \
                "$(xrandr -q | grep "$monitor" | sed 's/primary //' | cut -d " " -f 3 | cut -d "+" -f 1)" \
                'unknown' \
                "$monitor" \
                '1.0' \
                'false'
            ;;
    esac
}

get_monitor_property() {
    local data=$1
    local property=$2
    local res pos desc scale disabled

    IFS=$'\t' read -r res pos desc scale disabled <<< "$data"
    debug "data: $data"
    debug "description: $desc"

    case $property in
        resolution)     printf '%s' "$res" ;;
        position)       printf '%s' "$pos" ;;
        description)    printf '%s' "$desc" ;;
        scale)          printf '%s' "$scale" ;;
        disabled)       printf '%s' "$disabled" ;;
        *)              printf ''
    esac
}

get_monitor_resolution_list() {
    local monitor=$1

    case $BACKEND in
        wayland)
            hyprland_monitors |
                jq -r --arg monitor "$monitor" '.[] | select(.name == $monitor) | .availableModes | .[] | split("@")[0]' |
                awk '!seen[$0]++'
            ;;
        x11)
            xrandr -q |
                awk -v monitor="$monitor" '{if ($1 ~ monitor) {print_now = 1} if (print_now==1 && $1 ~ /^[1-9]/) {print $1}}'
            ;;
    esac
}

set_monitor_hypr_lua() {
    local monitor=$1
    local property=$2
    local value=$3
    local curr_resolution curr_position curr_scale

    data="$(get_monitor_data "$monitor")"
    curr_resolution="$(get_monitor_property "$data" resolution)"
    curr_position="$(get_monitor_property "$data" position)"
    curr_scale="$(get_monitor_property "$data" scale)"

    case $property in
        scale)
            [[ $monitor == "$MON_INT" && $value = "1.5" ]] && value=1.458333

            hyprctl eval "hl.monitor({ output='$monitor', mode='$curr_resolution', position='$curr_position', scale=$value, disabled=false })"
            notify "Set scale for $monitor to $value"
            ;;
        disabled)
            hyprctl eval "hl.monitor({ output='$monitor', disabled=$value, mirror='' })"
            notify "Set $monitor $([[ $value == true ]] && printf 'disabled' || printf 'enabled')"
            ;;
        resolution)
            hyprctl eval "hl.monitor({ output='$monitor', mode='$value', position='$curr_position', scale=$curr_scale, disabled=false })"
            notify "Set resolution for $monitor to $value"
            ;;
        mirror)
            hyprctl eval "hl.monitor({ output='$monitor', mode='$value', position='$curr_position', scale=$curr_scale, disabled=false, mirror='$value' })"
            notify "Set mirror for $monitor to $value"
            ;;
        *)
            die "monitor hypr_lua property unknown: $property / $value"
            ;;
    esac
}

set_monitor_hypr_conf() {
    local monitor=$1
    local property=$2
    local value=$3

    data="$(get_monitor_data "$monitor")"
    resolution="$(get_monitor_property "$data" resolution)"
    position="$(get_monitor_property "$data" position)"
    scale="$(get_monitor_property "$data" scale)"

    case $property in
        disabled)
            if [[ $value == true ]]; then
                hyprctl keyword monitor "$monitor,disable"
            else
                hyprctl keyword monitor "$monitor,$resolution,$position,$scale"
            fi
            ;;
        resolution)
            hyprctl keyword monitor "$monitor,$value,$position,$scale"
            ;;
        scale)
            [[ $monitor == "$MON_INT" && $value == 1.5 ]] && value=1.458333
            hyprctl keyword monitor "$monitor,$resolution,$position,$value"
            ;;
        mirror)
            hyprctl keyword monitor "$monitor,$resolution,$position,$scale,mirror,$value"
            ;;
        *)
            die "Propiedad Hyprland desconocida: $property"
            ;;
    esac
}

set_monitor_x11() {
    local monitor=$1
    local property=$2
    local value=$3
    local factor

    case $property in
        disabled)
            if [[ $value == true ]]; then
                xrandr --output "$monitor" --off
            elif [[ $monitor == "$MON_INT" ]]; then
                xrandr --output "$monitor" --auto
            else
                xrandr --output "$monitor" --auto --right-of "$MON_INT"
            fi
            ;;
        resolution)
            xrandr --output "$monitor" --mode "$value"
            ;;
        scale)
            case $value in
                1.0)    factor=1 ;;
                1.25)   factor=0.8 ;;
                1.33)   factor=0.751879 ;;
                1.5)    factor=0.666667 ;;
                2.0)    factor=0.5 ;;
                *)      die "Escala X11 no soportada: $value" ;;
            esac

            xrandr --output "$monitor" --scale "$factor"
            ;;
        mirror)
            xrandr --output "$monitor" --auto --same-as "$value"
            ;;
        *)
            die "Propiedad X11 desconocida: $property"
            ;;
    esac
}

set_monitor() {
    local monitor=$1
    local property=$2
    local value=$3

    if [[ $BACKEND == wayland && $HYPRCONF == lua ]]; then
        set_monitor_hypr_lua  "$monitor" "$property" "$value"

    elif [[ $BACKEND == wayland && $HYPRCONF == conf ]]; then
        set_monitor_hypr_conf "$monitor" "$property" "$value"

    elif [[ $BACKEND == x11 ]]; then
        set_monitor_x11  "$monitor" "$property" "$value"
    fi
}

get_lid_state() {
    cat /proc/acpi/button/lid/LID0/state | cut -d ":" -f 2 | xargs
}

switch_monitor_opt() {
    local monitor=$1
    local data

    data="$(get_monitor_data "$monitor")"

    debug "switch monitor opt $monitor  data $data"

    if (( $(count_monitors) > 1 )) && [ "$(get_lid_state)" == open ]; then
        if [[ $(get_monitor_property "$data" disabled) == false ]]; then
            if (( $(count_enabled_monitors) > 1 )); then
                debug "monitor $monitor disabled falso"
                printf '%s' "${OPTIONS[SET_OFF]}"
            fi
        else
            debug "monitor $monitor disabled true"
            printf '%s' "${OPTIONS[SET_ON]}"
        fi
    fi
}

get_backend() {
    MON_INT=eDP
    BACKEND=x11
    HYPRCONF=conf

    if [[ -n ${HYPRLAND_INSTANCE_SIGNATURE:-} ]] && command -v hyprctl >/dev/null 2>&1; then
        BACKEND=wayland
        MON_INT=eDP-1
    fi

    if [[ $BACKEND == wayland && -f "$XDG_CONFIG_HOME/hypr/hyprland.lua" ]]; then
        HYPRCONF=lua
    fi

    debug "Backend: $BACKEND / Internal Monitor: $MON_INT / HyprConf: $HYPRCONF"
}

menu_monitor_resolution() {
    local monitor=$1
    local resolution_list resolution

    resolution_list="$(get_monitor_resolution_list "$monitor")"
    resolution=$(menu "$resolution_list" "Resolucion $monitor")

    [[ -n "$resolution" ]] && set_monitor "$monitor" "resolution" "$resolution"
}

menu_monitor_props() {
    local monitor=$1
    local selected data monitor_desc switch_option
    local -a options=()

    data="$(get_monitor_data "$monitor")"

    debug "menu monitor props   monitor  $monitor   data $data"

    switch_option="$(switch_monitor_opt "$monitor")"
    [[ -n "$switch_option" ]] && options+=("$switch_option")

    if [[ $(get_monitor_property "$data" disabled) == false ]]; then
        options+=("${OPTIONS_ONE_MONITOR[@]}")
    fi

    monitor_desc=$(printf '%s (%s@%s scale %s)' \
                            "$(get_monitor_property "$data" description)" \
                            "$(get_monitor_property "$data" resolution)"  \
                            "$(get_monitor_property "$data" position)"    \
                            "$(get_monitor_property "$data" scale)")

    selected="$(menu "$(printf '%s\n' "${options[@]}")" "Monitor $monitor" "$monitor_desc")"

    [[ -n $selected ]] || exit 0

    case $selected in
        "${OPTIONS[SET_OFF]}")    set_monitor "$monitor" disabled true ;;
        "${OPTIONS[SET_ON]}")     set_monitor "$monitor" disabled false ;;
        "${OPTIONS[SCALE_100]}")  set_monitor "$monitor" scale 1.0 ;;
        "${OPTIONS[SCALE_125]}")  set_monitor "$monitor" scale 1.25 ;;
        "${OPTIONS[SCALE_133]}")  set_monitor "$monitor" scale 1.33 ;;
        "${OPTIONS[SCALE_150]}")  set_monitor "$monitor" scale 1.5  ;;
        "${OPTIONS[SCALE_200]}")  set_monitor "$monitor" scale 2.0  ;;
        "${OPTIONS[SET_RESOL]}")  menu_monitor_resolution "$monitor" ;;
    esac
}

apply_monitors_layout() {
    local profile=$1
    local monitor

    while IFS= read -r monitor; do
        case $profile in
            main)       set_monitor "$monitor" disabled \
                            "$([[ $monitor == "$MON_INT" ]] && printf false || printf true)"
                        ;;
            secondary)  set_monitor "$monitor" disabled \
                            "$([[ $monitor == "$MON_INT" ]] && printf true || printf false)"
                        ;;
            extend)     set_monitor "$monitor" disabled false
                        ;;
            duplicate)
                        if [[ $monitor == "$MON_INT" ]]; then
                            set_monitor "$monitor" disabled false
                        else
                            set_monitor "$monitor" mirror "$MON_INT"
                        fi
                        ;;

        esac
    done < <(list_monitors)

}

menu_select_monitors() {
    local selected monitor
    local -a options
    local -a monitor_options

    options=("${OPTIONS_MULTIPLE_MONITORS[@]}")
    mapfile -t monitor_options < <(get_monitor_list)
    options+=("${monitor_options[@]}")

    selected="$(menu "$( printf '%s\n' "${options[@]}" )" "Seleccione monitor")"
    [ -n "$selected" ] || exit 0

    case $selected in
        "${OPTIONS[SET_MAIN]}") apply_monitors_layout main ;;
        "${OPTIONS[SET_DUP]}")  apply_monitors_layout duplicate ;;
        "${OPTIONS[SET_EXT]}")  apply_monitors_layout extend ;;
        "${OPTIONS[SET_SEC]}")  apply_monitors_layout secondary ;;
        *)
            IFS=' ' read -r _ monitor _ <<< "$selected"
            debug "menu select monitors:  selected $selected    monitors $monitor"
            menu_monitor_props "$monitor"
            ;;
    esac
}

main() {
    local monitor_count

    get_backend
    monitor_count=$(count_monitors)

    case $monitor_count in
        0)  die "No monitors found" ;;
        1)  menu_monitor_props "$(list_monitors)" ;;
        *)  menu_select_monitors ;;
    esac
}

main

