#!/usr/bin/env bash

bluetooth_print() {
    if [[ "$(bluetooth_state)" == off ]]; then
        printf '%%{F#66FFFFFF}'
    else
        if bluetoothctl info | grep -q 'Device '; then
            printf ''
        else
            printf ''
        fi
    fi
}

bluetooth_toggle() {
    if bluetoothctl show | grep -q "Powered: no"; then
        bluetoothctl power on >> /dev/null

        printf 'Encendiendo bluetooth\n'
        sleep 1

        # while read -r _ device name; do
        #     printf 'Conectando device: %s (%s)\n' "$name" "$device"
        #     bluetoothctl --timeout 5 connect "$device" >> /dev/null
        # done < <(bluetoothctl devices | grep Device)
    else
        # Desconecta los dispositivos pareados
        while read -r _ device name; do
            printf 'Desconectando device: %s (%s)\n' "$name" "$device"
            bluetoothctl disconnect "$device" >> /dev/null
        done < <(bluetoothctl devices Connected | grep Device)

        bluetoothctl power off >> /dev/null
        printf 'Apagando bluetooth\n'
    fi
    notify-send -u low "Bluetooth" "Set bluetooth $(bluetooth_state)"
}

bluetooth_state() {
    bluetoothctl show | grep -q "Powered: no" && printf 'off' || printf 'on'
}

case "$1" in
    --toggle) bluetooth_toggle ;;
    --state)  bluetooth_state ;;
    *)        bluetooth_print ;;
esac
