#!/bin/bash

waybar_style=$HOME/.config/waybar/style.css
waybar_layout=$HOME/.config/waybar/config.jsonc

current_theme() {
    grep import $waybar_style | grep themes | cut -d "/" -f 2
}

change_theme() {
    # waybar
    sed -i "s/\".*\/style.css\"/\"themes\/$1\/style.css\"/" $waybar_style
    sed -i "s/\".*\/layout.jsonc\"/\"\$HOME\/\.config\/waybar\/themes\/$1\/layout.jsonc\"/" $waybar_layout
}

if [ ! -f "$waybar_style" ]; then
    cp "$waybar_style".orig "$waybar_style"
fi

if [ ! -f "$waybar_layout" ]; then
    cp "$waybar_layout".orig "$waybar_layout"
fi


if [ -n "$1" ]; then
    theme=$1
else
    temas=(Square Circle Underscore Mac Float Tahoe KDE)

    opts=""
    for i in "${temas[@]}"; do
        if [ "${i,,}" = "$(current_theme)" ]; then
            opts="$opts<i>$i</i>\n"
        else
            opts="$opts$i\n"
        fi
    done

    theme=$(echo -e $opts | rofi -dmenu -markup-rows -i -format p -p "")
fi

if [ -n "$theme" ]; then
    change_theme ${theme,,}
    [ "$DESKTOP_SESSION" = "bspwm" ] && bspc wm --restart || $HOME/.config/hypr/scripts/hypr-restore-waybar
    notify-send -u low "Theme" "Change theme to $theme"
fi

